In [1]:
### this program reads the consolidated trade file, makes a list of current holdings and gives delivery data for them for 5 days

In [2]:
master_file_path = "C:\\Users\\User\\Dropbox\\SQL Stock Market Data\\Python Code from ChatGPT\\Master File\\CompanyMaster.csv"
directory = "C:\\Users\\User\\Dropbox\\SQL Stock Market Data\\Data Files\\"  # Replace with the path to your directory
file_path = "C:\\Users\\User\\Dropbox\\TS Personal\\Trade Files\\Consolidated Trade File from 1st April 2022.xlsx"

output_path = "C:\\Users\\User\\Dropbox\\SQL Stock Market Data\\Python Code from ChatGPT\\Output File\\"

column_order = ['NSE_Code','BSE_Code','Date','NSE_Delivery','BSE_Delivery']

In [3]:
import os
import csv
import pandas as pd



def search_nse_code(directory, nse_code, no_days):
# Create an empty DataFrame to store the results
    nse_df = pd.DataFrame(columns=['NSE_Code', 'Date','NSE_Delivery'])
    dely_segment = ['EQ','BE','SM','ST']

    file_names = sorted([file for file in os.listdir(directory) if file.endswith('.csv') and file.startswith('NSE Delivery')], reverse=True)[:no_days]


    for file_name in file_names:
        file_path = os.path.join(directory, file_name)
        date = file_name[13:19]
            
        with open(file_path, 'r') as file:
            reader = csv.reader(file)
            found_match = False  # Flag variable to track the match
            for i, line in enumerate(reader, start=1):
                if i >= 5:  # Start reading from line 5
                    line_str = ','.join(line)
                    data = line_str.split(',')
                    if data[2] == nse_code and data[3] in dely_segment:
                        dely = data[5]
                        nse_df = nse_df.append({'NSE_Code': nse_code, 'Date': date, 'NSE_Delivery':dely}, ignore_index=True)
                        found_match = True
                        break
            if found_match:
                continue
            

    return nse_df

def search_bse_code(directory, bse_code, no_days):
    # Create an empty DataFrame to store the results
    bse_df = pd.DataFrame(columns=['BSE_Code', 'Date','BSE_Delivery'])
    dely_segment = ['EQ','BE','SM','ST']

    file_names = sorted([file for file in os.listdir(directory) if file.endswith('.txt') and file.startswith('BSE Gross Deliverable ')], reverse=True)[:no_days]


    for file_name in file_names:
        file_path = os.path.join(directory, file_name)
        date = file_name[22:28] 
    
        with open(file_path, 'r') as file:
            reader = csv.reader(file)
            found_match = False  # Flag variable to track the match
            for i, line in enumerate(reader, start=1):
                if i >= 2:  # Start reading from line 5
                    line_str = ','.join(line)
                    data = line_str.split('|')
                    if data[1] == bse_code:
                        dely = data[2]
                        bse_df = bse_df.append({'BSE_Code': bse_code, 'Date': date, 'BSE_Delivery':dely}, ignore_index=True)
                        found_match = True
                        break
            if found_match:
                continue
            
    return bse_df
                

def find_corresponding_codes(master_file_path, user_input):
    nse_code = ""
    bse_code = ""

    user_input = user_input.lower()  # Convert user input to lowercase for comparison

    with open(master_file_path, 'r') as file:
        reader = csv.reader(file)
        for row in reader:
            if row[1].lower() == user_input:  # NSE code match (case-insensitive)
                nse_code = row[1]
                bse_code = str(row[2])
                break
            elif row[2].lower() == user_input:  # BSE code match (case-insensitive)
                nse_code = row[1]
                bse_code = str(row[2])
                break

    return nse_code, bse_code

def format_value(value):
    return '{:,.0f}'.format(value)

def format_decimal(x):
    return '{:,.2f}'.format(x)

In [4]:
def search_nse_price(directory, nse_code, no_days):
# Create an empty DataFrame to store the results
    nse_df = pd.DataFrame(columns=['NSE_Code', 'Date','Price','Traded_Qty'])
    dely_segment = ['EQ','BE','SM','ST']

    file_names = sorted([file for file in os.listdir(directory) if file.lower().endswith(('CSV','.csv')) and file.startswith('NSE EQ')], reverse=True)[:no_days]


    for file_name in file_names:
        file_path = os.path.join(directory, file_name)
        date = file_name[7:13]
            
        with open(file_path, 'r') as file:
            reader = csv.reader(file)
            found_match = False  # Flag variable to track the match
            for row in reader:
                data_list = []
                data_list.append(row)
                    
                if data_list[0][0] == nse_code and data_list[0][1] in dely_segment:
                        price = data_list[0][5]
                        traded_qty = data_list[0][8]
                        nse_df = nse_df.append({'NSE_Code': nse_code, 'Date': date, 'Price':price, 
                                                'Traded_Qty': traded_qty}, ignore_index=True)
                        found_match = True
                        break
            if found_match:
                continue
            

    return nse_df

def search_bse_price(directory, bse_code, no_days):
# Create an empty DataFrame to store the results
    bse_df = pd.DataFrame(columns=['BSE_Code', 'Date','Price'])
    dely_segment = ['EQ','BE','SM','ST']

    file_names = sorted([file for file in os.listdir(directory) if file.lower().endswith(('CSV','csv')) and file.startswith('EQ ISIN')], reverse=True)[:no_days]


    for file_name in file_names:
        file_path = os.path.join(directory, file_name)
        date = file_name[8:14]
            
        with open(file_path, 'r') as file:
            reader = csv.reader(file)
            found_match = False  # Flag variable to track the match
            for row in reader:
                data_list = []
                data_list.append(row)
                    
                if data_list[0][0] == bse_code :
                        price = data_list[0][7]
                        bse_df = bse_df.append({'BSE_Code': bse_code, 'Date': date, 'Price':price}, ignore_index=True)
                        found_match = True
                        break
            if found_match:
                continue
            

    return bse_df

In [5]:
import openpyxl

def read_sheet_pivots(file_path, sheet_name):
    data = []
    workbook = openpyxl.load_workbook(file_path, read_only=True)
    sheet = workbook[sheet_name]
    
    row_number = 28
    column_m = 'M'
    column_n = 'N'
    
    
    while True:
        cell_m = sheet[column_m + str(row_number)].value
        cell_n = sheet[column_n + str(row_number)].value
        
        if cell_m is None and cell_n is None:
            break
        
        # Convert the cell values to strings and store them in the list
        if cell_m is not None:
            m_value = str(cell_m)
            if m_value != '0' and (not m_value.isdigit() or m_value.startswith('5')):
                data.append(m_value)
        
        if cell_n is not None:
            n_value = str(cell_n)
            if n_value != '0' and (not n_value.isdigit() or n_value.startswith('5')):
                data.append(n_value)
        
        row_number += 1
    
    return data

# Example usage

sheet_name = 'Pivots'
result_list = read_sheet_pivots(file_path, sheet_name)
print(result_list)

['UJJIVANSFB', 'REMSONSIND', 'MARINE', 'SATIN', 'ICICIBANK', '517429', 'KSOLVES', 'RISHABH', 'CANFINHOME', 'INDIGOPNTS', 'PURVA', 'L&tfh', 'JINDALSAW', 'IMAGICAA', 'KTKBANK', 'KOTAKBANK', 'TRIL', '543597', 'PRIMESECU', 'TARACHAND', 'ITDCEM', 'INDOTECH', 'MEDPLUS', 'HPL', 'EIHOTEL', '542753', 'UNIHEALTH', 'GOCOLORS', '531968', 'MANPASAND']

In [6]:
###from chatgpt -- to edit

import openpyxl
import pandas as pd

def read_sheet_pivots(file_path, sheet_name):
    data = []
    workbook = openpyxl.load_workbook(file_path, read_only=True)
    sheet = workbook[sheet_name]
    
    row_number = 28
    column_m = 'M'
    column_n = 'N'
    column_o = 'O'
    
    while True:
        cell_m = sheet[column_m + str(row_number)].value
        cell_n = sheet[column_n + str(row_number)].value
        cell_o = sheet[column_o + str(row_number)].value
        
        if cell_m is None and cell_n is None and cell_o is None:
            break
        
        if cell_m is not None:
            m_value = str(cell_m)
            if m_value != '0' and (not m_value.isdigit() or m_value.startswith('5')):
                data.append({'symbol': m_value, 'quantity': cell_o})
        
        if cell_n is not None:
            n_value = str(cell_n)
            if n_value != '0' and (not n_value.isdigit() or n_value.startswith('5')):
                data.append({'symbol': n_value, 'quantity': cell_o})
        
        row_number += 1
    
    holdings_df = pd.DataFrame(data)
    return holdings_df

# Example usage

#file_path = 'your_file_path.xlsx'  # Replace with the actual file path
sheet_name = 'Pivots'
holdings_df = read_sheet_pivots(file_path, sheet_name)
print(holdings_df)

        symbol  quantity
0   UJJIVANSFB    200000
1   REMSONSIND     13000
2       MARINE     60000
3        SATIN     15000
4    ICICIBANK      3000
5       517429     27700
6      KSOLVES      2000
7      RISHABH      4388
8   CANFINHOME      2500
9   INDIGOPNTS      1000
10       PURVA     10000
11       L&tfh     10000
12   JINDALSAW      3000
13    IMAGICAA     25000
14     KTKBANK      5000
15   KOTAKBANK       600
16        TRIL      5000
17      543597      3000
18   PRIMESECU      5000
19   TARACHAND      4000
20      ITDCEM      2500
21    INDOTECH      1000
22     MEDPLUS       584
23         HPL      2500
24     EIHOTEL      1000
25      542753     50000
26   UNIHEALTH      1000
27    GOCOLORS        82
28      531968      1612
29   MANPASAND      2000

In [7]:
##saving the holdings to csv for uploading to chartink and trading view

# Specify the name of the CSV file you want to create
csv_file_name = output_path + "0 My_Holdings.csv"

# Write the data to the CSV file
with open(csv_file_name, mode='w', newline='') as file:
    writer = csv.writer(file)
    writer.writerow(["Company"])  # Optional: Write a header row
    writer.writerows([[item] for item in result_list])

In [8]:
### displaying information for multiple scrips

scrips = result_list
no_days = 7

formatted_dfs = []


for i in scrips:
    nse_code, bse_code = find_corresponding_codes(master_file_path, i)
    
    nse_result = search_nse_code(directory, nse_code,no_days)
    bse_result = search_bse_code(directory, bse_code,no_days)
    
    #### search for price info in nse/bse files 

    nse_price = search_nse_price(directory,nse_code,no_days)
    nse_price['Price'] = nse_price['Price'].astype(float)
    
    if nse_result.empty:
        if nse_code == "":
            print('stock not in nse')
        else:
            print('stock in be or st, merging price_info')
            nse_merge = pd.merge(nse_price, nse_result, on='Date', how = 'left')
            data = {'NSE_Code': nse_merge['NSE_Code_x'],
                    'Date': nse_merge['Date'],
                    'NSE_Delivery': nse_merge['Traded_Qty']
                    }
            nse_result = pd.DataFrame(data)
            
            
    if nse_result.empty:
        merged_df = pd.merge(bse_result, nse_result, on='Date', how='left')
        merged_df['NSE_Delivery'] = merged_df['NSE_Delivery'].fillna(0)
        merged_df['NSE_Code'] = merged_df['NSE_Code'].fillna("")
# Check if bse_result is empty
    elif bse_result.empty:
        merged_df = pd.merge(nse_result, bse_result, on='Date', how='left')
        merged_df['BSE_Delivery'] = merged_df['BSE_Delivery'].fillna(0)
        merged_df['BSE_Code'] = merged_df['BSE_Code'].fillna("")
# Neither nse_result nor bse_result is empty
    else:
        merged_df = pd.merge(nse_result, bse_result, on='Date', how='inner')
        
    merged_df = merged_df[column_order]

    merged_df['NSE_Delivery'] = merged_df['NSE_Delivery'].astype(int)
    merged_df['BSE_Delivery'] = merged_df['BSE_Delivery'].astype(int)
    
    merged_df['Total_Delivery'] = merged_df['NSE_Delivery'] + merged_df['BSE_Delivery']
    
    nse_price = search_nse_price(directory,nse_code,no_days)
    nse_price['Price'] = nse_price['Price'].astype(float)

    if nse_price.empty:
        bse_price = search_bse_price(directory,bse_code,no_days)
        bse_price['Price'] = bse_price['Price'].astype(float)
        final_df = pd.merge(merged_df, bse_price, on=['Date','BSE_Code'], how='inner')
    else:
        final_df = pd.merge(merged_df, nse_price, on=['Date','NSE_Code'], how = 'inner')
        final_df.drop(columns='Traded_Qty', inplace=True)
    
    
##format the df for final printing/display
    formatted_df = final_df.style.format({'NSE_Delivery': format_value, 'BSE_Delivery': format_value, 
                                          'Total_Delivery': format_value, 'Price' : format_decimal}) 


    #formatted_df
    # Append the formatted DataFrame to the list
    #formatted_dfs.append(formatted_df)
    
    # Print the formatted DataFrame
    #print(f"Formatted DataFrame for {i}:")
    #print(formatted_df)
    #print("\n")  # Add a new line for separation
    
    print(f"Formatted DataFrame for {i}:")
    display(formatted_df)
    print("\n")  # Add a new line for separation

Formatted DataFrame for UJJIVANSFB:

stock in be or st, merging price_info
Formatted DataFrame for REMSONSIND:

stock in be or st, merging price_info
Formatted DataFrame for MARINE:

Formatted DataFrame for SATIN:

Formatted DataFrame for ICICIBANK:

stock not in nse
Formatted DataFrame for 517429:

stock in be or st, merging price_info
Formatted DataFrame for KSOLVES:

Formatted DataFrame for RISHABH:

Formatted DataFrame for CANFINHOME:

Formatted DataFrame for INDIGOPNTS:

Formatted DataFrame for PURVA:

Formatted DataFrame for L&tfh:

Formatted DataFrame for JINDALSAW:

Formatted DataFrame for IMAGICAA:

Formatted DataFrame for KTKBANK:

Formatted DataFrame for KOTAKBANK:

Formatted DataFrame for TRIL:

stock not in nse
Formatted DataFrame for 543597:

Formatted DataFrame for PRIMESECU:

Formatted DataFrame for TARACHAND:

Formatted DataFrame for ITDCEM:

stock in be or st, merging price_info
Formatted DataFrame for INDOTECH:

Formatted DataFrame for MEDPLUS:

Formatted DataFrame for HPL:

Formatted DataFrame for EIHOTEL:

stock not in nse
Formatted DataFrame for 542753:

Formatted DataFrame for UNIHEALTH:

Formatted DataFrame for GOCOLORS:

stock not in nse
Formatted DataFrame for 531968:

stock not in nse
Formatted DataFrame for MANPASAND:

In [9]:
## new code from chatgpt to check and edit


def print_quantity_symbols(symbols):
    print(", ".join(symbols))

scrips = result_list
no_days = 7

formatted_dfs = []

for i in scrips:
    nse_code, bse_code = find_corresponding_codes(master_file_path, i)

    # ... (existing code remains unchanged) ...

    # Format the df for final printing/display
    formatted_df = final_df.style.format({'NSE_Delivery': format_value, 'BSE_Delivery': format_value, 
                                          'Total_Delivery': format_value, 'Price': format_decimal})

    # Append the formatted DataFrame to the list
    formatted_dfs.append(formatted_df)

    # Print the quantity for the current symbol on top line
    quantity_symbols = [f"{i} ({formatted_df['Total_Delivery'].sum()})"]
    print_quantity_symbols(quantity_symbols)

# Print the DataFrames one by one
for i, formatted_df in zip(scrips, formatted_dfs):
    print(f"Formatted DataFrame for {i}:")
    print(formatted_df)
    print("\n")  # Add a new line for separation

TypeError: 'Styler' object is not subscriptable