In [1]:
#### run combined df again if any code changes occur (symbol change) including additions

In [12]:
#### combines 7 days delivery files
#### reads market cap from screener
#### reads averages

#### this reads non_fno_wl, yymmdd_volume_3x_wl, yymmdd_tview_wl_above_500, yymmdd_tview_wl_below_500, sme_csv
 

#### heading for reports
#### title for reports

In [2]:
# importing necessary modules 

import os
import pandas as pd
import csv
from pathlib import Path

base_folder = Path.cwd()
print(base_folder)

c:\Users\birap\OneDrive\Desktop\Tradeview\tradingView\Python code for chatGpt

In [3]:
###  datapath for lenovo desktop

master_file_dir = Path.joinpath(base_folder, "Master File")

master_file_path = Path.joinpath(base_folder, "Master File", "CompanyMaster.csv")
directory = Path.joinpath(Path(base_folder).parents[0], "Data Files")
combined_directory =  Path.joinpath(Path(base_folder).parents[0], "Delivery Price Combined Files")


input_path =  Path.joinpath(base_folder, "Input File")
output_path = Path.joinpath(base_folder, "Output File")

In [4]:
column_order = ['NSE_Code','BSE_Code','Date','NSE_Delivery','BSE_Delivery']


non_fno_csv = os.path.join(output_path, '0_non_fno.csv')
fno_csv = os.path.join(output_path, 'fno.csv')
sme_csv = os.path.join(output_path, 'sme_csv.csv')

avgs_file = os.path.join(input_path, 'NSE BSE Averages.xlsx')

In [89]:
#### reading nse and bse averages
file_path = avgs_file

# Replace 'Sheet1' with the name of the sheet you want to read
#sheet_name = 'Sheet1'
nse_averages = "NSE Averages"
bse_averages = "BSE Averages"

# Read the Excel file into a DataFrame
#df = pd.read_excel(file_path, sheet_name=sheet_name)

#nse_avg_df = pd.read_excel(file_path, sheet_name = nse_averages, dtype=column_width, engine='openpyxl')
nse_avg_df = pd.read_excel(file_path, sheet_name=nse_averages)
nse_avg_df['Name'] = nse_avg_df['Name'].str.replace('_T$',"",regex=True)
nse_avg_df['Name'] = nse_avg_df['Name'].str.replace('_Z$',"",regex=True)
nse_avg_df['Name'] = nse_avg_df['Name'].str.replace(' SM$',"",regex=True)
nse_avg_df['Name'] = nse_avg_df['Name'].str.replace(' ST$',"",regex=True)


nse_avg_df['Name'] = nse_avg_df['Name'].str.strip()


bse_avg_df = pd.read_excel(file_path, sheet_name = bse_averages)
bse_avg_df['Code'] = bse_avg_df['Code'].astype(str)


####################reading market cap file

mktcap_file = os.path.join(master_file_dir, 'MarketCap from Screener.csv')
mktcap_df = pd.read_csv(mktcap_file)
mktcap_df['BSE Code'] = mktcap_df['BSE Code'].fillna(0)
mktcap_df['BSE Code'] = mktcap_df['BSE Code'].astype(int)
mktcap_df['NSE Code'] = mktcap_df['NSE Code'].fillna("")

mktcap_df.rename(columns= { 'BSE Code' : 'BSE_Code', 
                          'NSE Code': 'NSE_Code'}, inplace =True)

mktcap_df.loc[mktcap_df['NSE_Code'] == "", "NSE_Code"] = mktcap_df['BSE_Code']

In [93]:

###### combine 7 days price files

no_days = 7

file_names = sorted([file for file in os.listdir(combined_directory) if file.lower().endswith(("CSV","csv"))
                        and file.startswith("combined")], reverse=True)[:no_days]

print(file_names)

count = 1

for file_name in file_names:
    file_path = os.path.join(combined_directory,file_name)
    csv_file_df = pd.read_csv(file_path)
    
    if count == 1:
        combined_df = csv_file_df
    else:
        combined_df = pd.concat([combined_df, csv_file_df], ignore_index=True)
    
    count += 1
    #print(count)

combined_df['BSE_Code'] = combined_df['BSE_Code'].fillna(0)
combined_df['BSE_Code'] = combined_df['BSE_Code'].astype(int)
combined_df['NSE_Code'] = combined_df['NSE_Code'].fillna("")
combined_df['Company Name'] = combined_df['Company Name'].fillna("")
combined_df['NSE_Code'] = combined_df.apply(replace_nse_code, axis=1)

# Assuming your DataFrame is named combined_df
report_date = combined_df['Date'].max()
report_date = str(report_date)

print(report_date)

['combined_231020.csv', 'combined_231010.csv', 'combined_230810.csv', 'combined_230420.csv', 'combined_190124.csv']
231020

In [91]:
def find_corresponding_codes(master_file_path, user_input):
    nse_code = ""
    bse_code = ""
    co_name = ""

    user_input = user_input.lower()  # Convert user input to lowercase for comparison

    with open(master_file_path, 'r') as file:
        reader = csv.reader(file)
        for row in reader:
            if row[1].lower() == user_input:  # NSE code match (case-insensitive)
                nse_code = row[1]
                bse_code = str(row[2])
                co_name = row[0]
                break
            elif row[2].lower() == user_input:  # BSE code match (case-insensitive)
                nse_code = row[1]
                bse_code = str(row[2])
                co_name = row[0]
                break

    return nse_code, bse_code,co_name

def format_value(value):
    return '{:,.0f}'.format(value)

def format_decimal(x):
    return '{:,.2f}'.format(x)

def averages(scrip_code):
    ema10 = [0]  # Default value for ema10
    ema20 = [0]  # Default value for ema20
    ema50 = [0]  # Default value for ema50
    ema200 = [0]  # Default value for ema200
    
    
        
    if type(scrip_code) == int:
        scrip_code = str(scrip_code)
        averages_df = bse_avg_df[bse_avg_df['Code'] == scrip_code]
    else:
        scrip_code = scrip_code.upper()
        averages_df = nse_avg_df[nse_avg_df['Name'] == scrip_code]
    
    if not averages_df.empty:
        ema10 = averages_df['ema10'].values.tolist()
        ema20 = averages_df['ema20'].values.tolist()
        ema50 = averages_df['ema50'].values.tolist()
        ema200 = averages_df['ema200'].values.tolist()
    
    return ema10, ema20, ema50, ema200


def get_mktcap(scrip_code):
    
    if type(scrip_code) == int:
        #scrip_code = str(scrip_code)
        scrip_mktcap_df = mktcap_df[mktcap_df['BSE_Code'] == scrip_code]
    else:
        scrip_code = scrip_code.upper()
        scrip_mktcap_df = mktcap_df[mktcap_df['NSE_Code'] == scrip_code]
        
    #scrip_mktcap_df.info()
    
    if not scrip_mktcap_df.empty:
        scrip_mktcap = scrip_mktcap_df['Market Capitalization'].values.tolist()
        
    else:
        scrip_mktcap = [0]
    
    return scrip_mktcap


def get_networth(scrip_code):
    
    if type(scrip_code) == int:
        #scrip_code = str(scrip_code)
        scrip_mktcap_df = mktcap_df[mktcap_df['BSE_Code'] == scrip_code]
    else:
        scrip_code = scrip_code.upper()
        scrip_mktcap_df = mktcap_df[mktcap_df['NSE_Code'] == scrip_code]
        
    #scrip_mktcap_df.info()
    
    if not scrip_mktcap_df.empty:
        scrip_networth = scrip_mktcap_df['Net worth'].values.tolist()
        
    else:
        scrip_networth = [0]
    
    return scrip_networth
     
    
    
def replace_nse_code(row):
    if pd.isna(row['NSE_Code']) or row['NSE_Code'] == "":
        return row['BSE_Code']
    else:
        return row['NSE_Code']

# Apply the custom function to the NSE_Code column

def list_process(list_name):
    list_name_lower = [item.lower() for item in list_name]
    nse_code_df = combined_df[combined_df['NSE_Code'].str.lower().isin(list_name_lower)]
    
    numeric_list_name = []
    
    for value in list_name:
        if value.isdigit():
            numeric_list_name.append(int(value))
    
    bse_code_df = combined_df[combined_df['BSE_Code'].isin(numeric_list_name)]
    final_code_df = pd.concat([nse_code_df,bse_code_df], ignore_index=True)
    final_code_df['NSE_Code'] = final_code_df.apply(replace_nse_code, axis=1)
    
    final_code_df.sort_values(by=['NSE_Code', 'Date'], ascending=[True, False], inplace=True)
    grouped_df = final_code_df.groupby('NSE_Code')
    
    for name, group in grouped_df:
        
        ema10, ema20, ema50, ema200 = averages(str(name))
        ema_str = "ema10 / ema20 / ema50 / ema200"
    
        print("")
        print(f"Company Name: {group['Company Name'].iloc[0]} (NSE Code: {name}, BSE Code: {group['BSE_Code'].iloc[0]})")
        print(f"{ema_str}     {ema10[0]}  {ema20[0]}  {ema50[0]}  {ema200[0]}")
        print("")

        # Format the columns before printing
        group['NSE_Delivery'] = group['NSE_Delivery'].apply(lambda x: '{:,.0f}'.format(x))
        group['BSE_Delivery'] = group['BSE_Delivery'].apply(lambda x: '{:,.0f}'.format(x))
        group['Total_Delivery'] = group['Total_Delivery'].apply(lambda x: '{:,.0f}'.format(x))

        # Print the header with column names excluding 'NSE_Code' and 'BSE_Code'
        header = ['Date', 'NSE_Delivery', 'BSE_Delivery', 'Total_Delivery', 'Price']
    
        # Print the table with manual formatting
        print(f"{'Date':<8}{'NSE_Delivery':>15}{'BSE_Delivery':>15}{'Total_Delivery':>20}{'Price':>15}")
        for _, row in group[header].iterrows():
            print(f"{row['Date']:<8}{row['NSE_Delivery']:>15}{row['BSE_Delivery']:>15}{row['Total_Delivery']:>20}{row['Price']:>15.2f}")

        # Add two blank spaces between groups
        print("\n")
        

    
    return final_code_df
    
    
def list_process_new(list_name, header):
    
    print(header)
    
    for company in list_name:
    # Filter the DataFrame for the current company
    
        if company.isdigit():
            company_int = int(company)
            company_data = combined_df[combined_df['BSE_Code'] == company_int]
            #print(company)
        else:
            company = company.upper()
            company_data = combined_df[combined_df['NSE_Code'] == company]
            #print(company)

        # Check if the DataFrame is not empty
        if not company_data.empty:
            # Extract relevant information
            company_name = company_data['Company Name'].values[0]
            nse_code = company_data['NSE_Code'].values[0]
            bse_code = company_data['BSE_Code'].values[0]

            ema10,ema20,ema50,ema200 = averages(nse_code)
            ema_str = "ema10 / ema20 / ema50 / ema200"
            
            mktcap_value = get_mktcap(nse_code)
            networth_value = get_networth(nse_code)
            
            print(f"Company Name: {company_name} (NSE Code: {nse_code}, BSE Code: {bse_code}, Mktcap:{mktcap_value[0]:,.0f}, Networth:{networth_value[0]:,.0f})")

            print("")
        
            print(f"{ema_str}     {ema10[0]}  {ema20[0]}  {ema50[0]}  {ema200[0]}")
            print("")

            # Format and print the specified columns with additional spaces
            formatted_columns = ['Date', 'NSE_Delivery', 'BSE_Delivery', 'Total_Delivery', 'Price']
            formatted_data = company_data[formatted_columns].copy()
            formatted_data['NSE_Delivery'] = formatted_data['NSE_Delivery'].apply(lambda x: f"{int(x):,}")
            formatted_data['BSE_Delivery'] = formatted_data['BSE_Delivery'].apply(lambda x: f"{int(x):,}")
            formatted_data['Total_Delivery'] = formatted_data['Total_Delivery'].apply(lambda x: f"{int(x):,}")
            formatted_data['Price'] = formatted_data['Price'].apply(lambda x: f"{x:.2f}")

            # Adjust the spacing between columns
            formatted_data_str = formatted_data.to_string(index=False, 
                                                      col_space={'Date':9,
                                                                 'NSE_Delivery':15,
                                                                 'BSE_Delivery':15,
                                                                 'Total_Delivery': 15, 
                                                                 'Price': 10
                                                                 }
                                                        )

            print(formatted_data_str)
            # Add a line break between companies
            print("\n" + "=" * 50 + "\n")
            print("")
        else:
            print(f"No data found for {company}\n")

    
def add_nse_prefix(df, column_name):
    # Create a copy of the DataFrame to avoid SettingWithCopyWarning
    df = df.copy()

    # Add "NSE:" prefix to the specified column
    df.loc[:, column_name] = "NSE:" + df[column_name].astype(str)

    return df

In [107]:
def print_formatted_rows(stock_list, title):
    # Print the header
    header = "Company Name".ljust(35) + "StockCode".ljust(10) + "Close".rjust(10) + "PrevClose".rjust(10) + \
             "MktCap".rjust(10) + "EMA10".rjust(10) + "EMA20".rjust(10) + "EMA50".rjust(10) + "EMA200".rjust(10)
    print(title)
    print("")
    print("")
    print(header)
    print("")
    print("")

    line_counter = 0
    
    for stock in stock_list:
        if stock.isdigit():
            stock_code = int(stock)
            df_row = combined_df[combined_df['BSE_Code'] == stock_code]
        else:
            stock_code = stock.upper()
            df_row = combined_df[combined_df['NSE_Code'] == stock_code]

        if not df_row.empty:
            company_name = df_row['Company Name'].values[0]
            stock_code = df_row['NSE_Code'].values[0]
            price = df_row['Price'].values[0]
            prevclose = df_row['PrevClose'].values[0]

            ema10, ema20, ema50, ema200 = averages(stock_code)
            ema10 = ema10[0]
            ema20 = ema20[0]
            ema50 = ema50[0]
            ema200 = ema200[0]

            mktcap_value = get_mktcap(stock_code)
            mktcap = mktcap_value[0]

            # Format the values with ljust and rjust
            formatted_row = company_name.ljust(35) + str(stock_code).ljust(10) + \
                             f"{price:.2f}".rjust(10) + f"{prevclose:.2f}".rjust(10) + \
                             f"{mktcap:,.0f}".rjust(10) + f"{ema10:.2f}".rjust(10) + \
                             f"{ema20:.2f}".rjust(10) + f"{ema50:.2f}".rjust(10) + f"{ema200:.2f}".rjust(10)

            print(formatted_row)
            
            line_counter += 1

            # Insert a blank line after every 5 lines
            if line_counter % 5 == 0:
                print()

In [94]:
### reading csv of top 50 by value and volume in delivery

non_fno_df_in = pd.read_csv(non_fno_csv)
fno_df = pd.read_csv(fno_csv)
sme_df_in = pd.read_csv(sme_csv)

"""It fills the missing (NaN) values in the 'NSE_Code' column of the DataFrame non_fno_df with values 
from the 'BSE_Code' column converted to strings.

The .astype(str) part is used to convert the values in the 'BSE_Code' column to strings. 
This is necessary because the 'NSE_Code' column likely contains strings (object dtype), and 
you need to ensure that the replacement values are of the same data type.

The fillna method is used to perform the filling operation. By setting the inplace parameter to True, 
the operation is performed directly on the DataFrame without the need to assign the result back to the DataFrame."""


def fill_missing_nse_code(data_frame):
    # Convert non-finite 'BSE_Code' values to integers while replacing NaN with a placeholder
    placeholder_int = -1  # Placeholder integer value for NaN
    data_frame['BSE_Code'] = data_frame['BSE_Code'].fillna(placeholder_int).astype(int)
    
    # Convert 'BSE_Code' values to strings and fill missing 'NSE_Code' values
    data_frame['NSE_Code'].fillna(data_frame['BSE_Code'].astype(str), inplace=True)

    return data_frame


non_fno_df = fill_missing_nse_code(non_fno_df_in)
sme_df = fill_missing_nse_code(sme_df_in)

#non_fno_df['NSE_Code'].fillna(non_fno_df['BSE_Code'].astype(int).astype(str), inplace=True)
#sme_df['NSE_Code'].fillna(sme_df['BSE_Code'].astype(int).astype(str), inplace=True)

# Get the unique 'NSE_Code' values as a list
unique_non_fno = non_fno_df['NSE_Code'].unique().tolist()
sme_list = sme_df['NSE_Code'].unique().tolist()

focus_list = [ '531112', '538734', '543953', '543971', 'adanipower', 'amber', 'anantraj', 'angelone', 'anup', 'apollo', 
           'arvind', 'arvindfasn', 'bajajhind', 'bclind', 'bluejet', 'bluestarco', 'brigade', 'bse', 'cdsl', 'chembond', 
           'cignititec', 'creditacc', 'cupid', 'daawat', 'dbrealty', 'dharmaj', 'diamondyd', 'elecon', 'electcast', 
           'emil', 'focus', 'gabriel', 'gensol', 'genuspower', 'hblpower', 'hirect', 'hitech', 'hpl', 'idea', 'hcc',
           'ifglexpor', 'iiflsec', 'ikio', 'indotech', 'inoxwind', 'jindalsaw', 'jkcement', 'jklakshmi', '530129',
           'jktyre', 'jpassociat', 'jppower', 'jwl', 'kapston', 'kesoramind', 'kpittech', 'l&tfh', 'lalpathlab', 'tv18brdcst',
           'lodha', 'marine', 'mblinfra', 'mcx', 'newgen', 'paytm', 'peninland', 'pfs', 'repcohome','ndrauto','magson',
           'phoenixltd', 'pplpharma', 'premexpln', 'prestige', 'pyramid', 'radico', 'rategain', 'recltd', '522101',
           'rkforge', 'rpglife', 'sadhnaniq', 'sanghvimov', 'satin', 'sdbl', 'senco', 'sepc', 'shriramfin','shrirampps', 
            'skygold', 'solarinds', 'sonatsoftw', 'spandana', 'suzlon', 'tatamotors', 'thomascook', 'shripiston',
           'titagarh', 'tril', 'unionbank', 'vijaya', 'walchannag', 'welspunind', 'zaggle', 'zeemedia', 'zomato',
           'hariompipe', 'semac', 'tci', '540358', 'icil', '20microns', 'prsmjohnsn', 'poonawalla', 'cello', 'hcc', 
          'bikaji', 'neulandlab', 'jppower', 'trent']

In [95]:
dely_3x = os.path.join(output_path, f'_{report_date}_0_volume_3x_wl.csv')
dely_3x_df = pd.read_csv(dely_3x)
dely_3x_df.head()

           Symbol
0  NSE:PLAZACABLE
1      NSE:541701
2      NSE:514010
3      NSE:512329
4  NSE:GKWLIMITED

In [96]:

#dely_3x_list = dely_3x_df.tolist()
# Extract the 'ScripCode' column from the DataFrame
dely_3x_list = dely_3x_df['Symbol'].tolist()

cleaned_list = [stock.replace('NSE:', '') for stock in dely_3x_list]
dely_3x_list = cleaned_list

# Extract the first 50 records of the 'ScripCode' column from the DataFrame
#dely_3x_list = dely_3x_df['ScripCode'].head(50).tolist()

#dely_3x_list

In [97]:
### above 500 cr

# percent_new_high = os.path.join(output_path, f'_{report_date}_0_tview_wl_above_500.csv')
percent_new_high =r"C:\Users\birap\OneDrive\Desktop\Tradeview\tradingView\Python code for chatGpt\Output File\_231221_0_tview_wl_above_500.csv"
percent_new_high_df = pd.read_csv(percent_new_high)

percent_new_high_df.head()

           Ticker
0      NSE:VERTOZ
1    NSE:ARMANFIN
2     NSE:TARSONS
3  NSE:LOKESHMACH
4   NSE:PHANTOMFX

In [98]:
# Replace "NSE:" with an empty string in the 'Ticker' column
percent_new_high_df['Ticker'] = percent_new_high_df['Ticker'].str.replace('NSE:', '')

# Assuming percent_new_high_df is your DataFrame

# Replace "NSE:" with an empty string in the 'Ticker' column
percent_new_high_df['Ticker'] = percent_new_high_df['Ticker'].str.replace('NSE:', '')

# Print the updated DataFrame
#print(percent_new_high_df)

# Convert the 'Ticker' column to a list
ticker_list = percent_new_high_df['Ticker'].tolist()

#print(ticker_list)


#### below 500 cr

# percent_below = os.path.join(output_path, f'_{report_date}_0_tview_wl_below_500.csv')

# percent_below_df = pd.read_csv(percent_below)
percent_below = r"C:\Users\birap\OneDrive\Desktop\Tradeview\tradingView\Python code for chatGpt\Output File\_231221_0_tview_wl_below_500.csv"
percent_below_df = pd.read_csv(percent_below)

In [99]:
percent_below_df.head()

           Ticker
0       NSE:SIKKO
1    NSE:STARTECK
2     NSE:HINDCON
3  NSE:CORALFINAC
4  NSE:VISESHINFO

In [100]:
percent_below_df['Ticker'] = percent_below_df['Ticker'].str.replace("NSE:","")
ticker_below = percent_below_df["Ticker"].tolist()

In [101]:
import openpyxl

file_path = "C:\\Users\\sarda\\Dropbox\\TS Personal\\Trade Files\\Consolidated Trade File from 1st April 2022.xlsx"
def read_sheet_pivots(file_path, sheet_name):
    data = []
    workbook = openpyxl.load_workbook(file_path, read_only=True)
    sheet = workbook[sheet_name]
    
    row_number = 28
    column_m = 'M'
    column_n = 'N'
    
    
    while True:
        cell_m = sheet[column_m + str(row_number)].value
        cell_n = sheet[column_n + str(row_number)].value
        
        if cell_m is None and cell_n is None:
            break
        
        # Convert the cell values to strings and store them in the list
        if cell_m is not None:
            m_value = str(cell_m)
            if m_value != '0' and (not m_value.isdigit() or m_value.startswith('5')):
                data.append(m_value)
        
        if cell_n is not None:
            n_value = str(cell_n)
            if n_value != '0' and (not n_value.isdigit() or n_value.startswith('5')):
                data.append(n_value)
        
        row_number += 1
    
    return data

# Example usage

sheet_name = 'Pivots'
holding_list = read_sheet_pivots(file_path, sheet_name)
print(holding_list)


##saving the holdings to csv for uploading to chartink and trading view

# Specify the name of the CSV file you want to create
csv_file_name = output_path + "0 My_Holdings.csv"

# Write the data to the CSV file
with open(csv_file_name, mode='w', newline='') as file:
    writer = csv.writer(file)
    writer.writerow(["Company"])  # Optional: Write a header row
    writer.writerows([[item] for item in holding_list])

FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\sarda\\Dropbox\\TS Personal\\Trade Files\\Consolidated Trade File from 1st April 2022.xlsx'

In [102]:
# Remove duplicates and sort the list in-place
#my_list = list(set(my_list))
#my_list.sort()

list_below_1000 = ['522101','530129','538734','540358','540358','543953','543971','20microns','annapurna',
                   'arihantsup','chembond','dharmaj','global','indotech','kapston','kotharipet','magson',
                   'mblinfra','modisonltd','ndrauto','pyramid','semac','skygold','venusrem','walchannag']

list_below_1000 = list(set(list_below_1000))
list_below_1000.sort()


list_1k_10k = ['531112','542669','543620','anantraj','anup','apollo','arvind','arvindfasn','bajajhind','bancoindia',
               'bclind','bluejet','cignititec','cupid','dbrealty','diamondyd','dollar','electcast','emil','focus',
               'forcemot','gabriel','gensol','genuspower','hariompipe','hblpower','hcc','hirect','hitech','hpl',
               'icil','ifglexpor','iiflsec','ikio','inoxwind','jklakshmi','jktyre','jpassociat','jppower','kalamandir',
               'kesoramind','kfintech','kpigreen','ltfoods','lumaxtech','maninds','marine','moil','mvgjl','neulandlab',
               'newgen','paragmilk','peninland','pfs','pokarna','premexpln','prsmjohnsn','ramky','rategain','repcohome',
               'rpglife','sadhnaniq','sanghvimov','satin','sdbl','senco','sepc','shripiston','shrirampps','skipper',
               'somanycera','spandana','tci','tdpowersys','thomascook','tril','tv18brdcst','vijaya','zaggle',
               'zeemedia','awhcl','indramedco','marksans']

list_1k_10k = list(set(list_1k_10k))
list_1k_10k.sort()

list_above_10k = ['adanipower','amber','angelone','bikaji','bluestarco','brigade','bse','cdsl','cello','concordbio',
                  'creditacc','elecon','idea','jindalsaw','jkcement','jwl','kpittech','l&tfh','lalpathlab','lodha',
                  'mcx','patanjali','paytm','phoenixltd','piind','poonawalla','pplpharma','prestige','radico',
                  'recltd','rkforge','shriramfin','solarinds','sonatsoftw','suzlon','tatamotors','titagarh','trent',
                  'unionbank','welspunind','zomato','medanta','swanenergy','welcorp']

list_above_10k = list(set(list_above_10k))
list_above_10k.sort()

In [103]:
heading_non_fno = "          Top 50 7-day deliveries non_fno " + report_date
heading_sme = "          Top 50 7-day deliveries sme " + report_date

heading_3_percent = "          7-day deliveries up_3_percent or new_highs above 500 cr " + report_date
heading_3_percent_below = "          7-day deliveries up_3_percent or new_highs below 500 cr " + report_date

heading_3x = "          7-day deliveries 3x dely volume " + report_date
heading_holding = "          7-day deliveries for holdings " + report_date

heading_above_10k = "          7-day deliveries mktcap above 10k cr " + report_date
heading_below_1000 = "          7-day deliveries mktcap below 1000 cr " + report_date
heading_1k_10k = "            7-day deliveries mktcap 1k - 10k cr " + report_date

In [104]:
title_non_fno = "Non_fno top deliveries " + report_date + " with averages"
title_sme = "SME top deliveries " + report_date + " with averages"

title_3_percent = "         up_3_percent or new_highs above 500 cr " + report_date + " with averages"
title_3_percent_below = "         up_3_percent or new_highs below 500 cr " + report_date + " with averages"

title_3x = "          3x dely volume deliveries " + report_date + " with averages"
title_holding = "          7-day deliveries for holdings " + report_date + " with averages"

title_above_10k = "         Top deliveries mktcap above 10k cr " + report_date + " with averages"
title_below_1000 = "         Top deliveries mktcap below 1000 cr " + report_date + " with averages"
title_1k_10k = "          Top deliveries mktcap 1k - 10k cr " + report_date + " with averages"

In [105]:
ticker_list

['VERTOZ',
 'ARMANFIN',
 'TARSONS',
 'LOKESHMACH',
 'PHANTOMFX',
 'HINDCOPPER',
 'IMPAL',
 'INDOBORAX',
 'VINYAS',
 'NAVKARCORP',
 'SHYAMMETL',
 'SANGHVIMOV',
 'SANGAMIND',
 'ZENSARTECH',
 'APCL',
 'FCSSOFT',
 'BEML',
 'PCJEWELLER',
 'EMKAYTOOLS',
 'SALASAR',
 'MANALIPETC',
 'ZIMLAB',
 'GOLDIAM',
 'MOREPENLAB',
 'VIKASECO',
 'INOXWIND',
 'MSTCLTD',
 'VERANDA',
 'NECLIFE',
 'MTNL',
 'THYROCARE',
 'DEEPENR',
 'METROPOLIS',
 'GAEL',
 'HERITGFOOD',
 'SJVN',
 'COFFEEDAY',
 'HBLPOWER',
 'IIFLSEC',
 'INOXGREEN',
 'IRFC',
 'JASH',
 'GUFICBIO',
 'SATIN',
 'IRB',
 'TFCILTD',
 'ORIANA',
 'IRCTC',
 'WOCKPHARMA',
 'AGSTRA',
 'CHEMPLASTS',
 'ARIHANTSUP',
 'SNOWMAN',
 'WINDMACHIN',
 'GALLANTT',
 'TBZ',
 'HMVL',
 'SONACOMS',
 'DELHIVERY',
 'COCHINSHIP',
 'EXCELINDUS',
 'GEOJITFSL',
 'RPOWER',
 'RATEGAIN',
 'TTKHLTCARE',
 'NLCINDIA',
 'ZUARIIND',
 'RPSGVENT',
 'MARKSANS',
 'MASTEK',
 'SYNCOMF',
 'RAMCOSYS',
 'VENUSREM',
 'NATIONALUM',
 'ACE',
 'AUROPHARMA',
 'GLOBAL',
 'KELLTONTEC',
 'PRICOLLTD',
 'THEMISMED',
 'ARTEMISMED',
 'NMDC',
 'PGEL',
 'CYIENT',
 'GREENPLY',
 'ASHIANA',
 'BLISSGVS',
 'BCG',
 'BANCOINDIA',
 'INDOCO',
 'DBL',
 'DMCC',
 'CREST',
 'BGRENERGY',
 'AMIORG',
 'NAGAFERT',
 'RPGLIFE',
 'NHPC',
 'JUBLPHARMA',
 'TV18BRDCST',
 'SAIL',
 'SCHAND',
 'RTNINDIA',
 'MUKANDLTD',
 'SCHNEIDER',
 'GOCLCORP',
 'KILITCH',
 'SHRIPISTON',
 'KAMATHOTEL',
 'VISHNUINFR',
 '63MOONS',
 'OMINFRAL',
 'PANACEABIO',
 'ITDCEM',
 'BETA',
 'PARACABLES',
 'MARINE',
 'ACI',
 'HMT',
 'BHEL',
 'LALPATHLAB',
 'TRACXN',
 'KSOLVES',
 'STAR',
 'JKTYRE',
 'CHAMBLFERT',
 'JKIL',
 'ACL',
 'ISGEC',
 'IREDA',
 'ZEEMEDIA',
 'CAPACITE',
 'NFL',
 'HARDWYN',
 'ADANIGREEN',
 'PREMEXPLN',
 'TITAGARH',
 'ALLCARGO',
 'VMART',
 'FACT',
 'ESABINDIA',
 'VISHNU',
 'MOIL',
 'BIGBLOC',
 'MADRASFERT',
 'CONTROLPR',
 'PDSL',
 'JWL',
 'INFIBEAM',
 'DISHTV',
 'RTNPOWER',
 'PARAGMILK',
 'WEBELSOLAR',
 'KAMDHENU',
 'KIRIINDUS',
 'BBTC',
 'MKPL',
 'OIL',
 'SHAKTIPUMP',
 'BALMLAWRIE',
 'GLENMARK',
 'RAMKY',
 'NSLNISP',
 'CASTROLIND',
 'GSFC',
 'HTMEDIA',
 'BDL',
 'UCOBANK',
 'IDEA',
 'HERCULES',
 'ROTO',
 'ORCHPHARMA',
 'INDIASHLTR',
 'INDOAMIN',
 'UGROCAP',
 'GENUSPOWER',
 'URJA',
 'CEATLTD',
 'JMFINANCIL',
 'BALAMINES',
 'GPPL',
 'TEXRAIL',
 'ZEEL',
 'SUZLON',
 'ANANTRAJ',
 'REPCOHOME',
 'CHEMFAB',
 'GMDCLTD',
 'XCHANGING',
 'NAZARA',
 'DIXON',
 'PUNJABCHEM',
 'GIPCL',
 'HUDCO',
 'JTLIND',
 'FOCUS',
 'PRINCEPIPE',
 'PATELENG',
 'TEGA',
 'PPL',
 'VASCONEQ',
 'SPCENET',
 'SPARC',
 'WONDERLA',
 'AVALON',
 'RIIL',
 'AGARIND',
 'SOUTHBANK',
 'CELLECOR',
 'SUNFLAG',
 'INTLCONV',
 'JINDRILL',
 'LGBBROSLTD',
 'SASTASUNDR',
 'PAYTM',
 'NBCC',
 'SUDARSCHEM',
 'SEQUENT',
 'HEIDELBERG',
 'PFS',
 'NIITMTS',
 'HPAL',
 'IRMENERGY',
 'PRUDENT',
 'IBREALEST',
 'KFINTECH',
 'PPLPHARMA',
 'SRHHYPOLTD',
 'HFCL',
 'TEXINFRA',
 'KRITI',
 'RADIOCITY',
 'METROBRAND',
 'MAZDOCK',
 'JAGSNPHARM',
 'BCLIND',
 'HARIOMPIPE',
 'ICEMAKE',
 'CRAFTSMAN',
 'LTFOODS',
 'SHK',
 'KANORICHEM',
 'IBULHSGFIN',
 'DEN',
 'PLASTIBLEN',
 'RCF',
 'MANAPPURAM',
 'AVADHSUGAR',
 'WINDLAS',
 'GODREJPROP',
 'GANDHITUBE',
 'HINDWAREAP',
 'DCMSRIND',
 'INDRAMEDCO',
 'SAGCEM',
 'GANESHHOUC',
 'ZOTA',
 'SUTLEJTEX',
 'PENIND',
 'MANGLMCEM',
 'LINDEINDIA',
 'IWEL',
 '20MICRONS',
 'PNB',
 'PURVA',
 'SHANTIGEAR',
 'VSSL',
 'GREENPOWER',
 'MCX',
 'AARTIIND',
 'IOC',
 'STCINDIA',
 'AXITA',
 'SANDUMA',
 'BOMDYEING',
 'NUVOCO',
 'KAMOPAINTS',
 'VINYLINDIA',
 'JSL',
 'HLVLTD',
 'CENTRALBK',
 'SPIC',
 'ALOKINDS',
 'ENDURANCE',
 'SATINDLTD',
 'KPITTECH',
 'RSYSTEMS',
 'MMFL',
 'AMNPLST',
 'GESHIP',
 'HAPPSTMNDS',
 'KIOCL',
 'INSECTICID',
 'NETWORK18',
 'SHALBY',
 'NETWEB',
 'BECTORFOOD',
 'SUBEXLTD',
 'HEMIPROP',
 'SARDAEN',
 'APOLLO',
 'BEPL',
 'ADVENZYMES',
 'JAICORPLTD',
 'THOMASCOOK',
 'UFLEX',
 'ALEMBICLTD',
 'SBFC',
 'GMMPFAUDLR',
 'XPROINDIA',
 'REPRO',
 'FCL',
 'BIRLACORPN',
 'YESBANK',
 'SOTL',
 'PANAMAPET',
 'HCC',
 'THEINVEST',
 'AURIONPRO',
 'DHANBANK',
 'DHUNINV',
 'ALLETEC',
 'RVNL',
 'SCI',
 'IOB',
 'RITCO',
 'KECL',
 'LAOPALA',
 'MINDTECK',
 'KOTHARIPET',
 'JSWENERGY',
 'PRAKASH',
 'DEEPAKNTR',
 'ANANDRATHI',
 'VBL',
 'POCL',
 'KHAICHEM',
 'KIRLOSENG',
 'TORNTPHARM',
 'DOMS',
 'FORTIS',
 'NINSYS',
 'MUFIN']

In [151]:
from reportlab.lib.pagesizes import A4
from reportlab.pdfgen import canvas
from reportlab.lib import colors
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, PageBreak

def create_table_with_header(df, add_column_names=False, table_width=None):
    """create a table with header and data"""
    table_data = [df.columns.tolist()] + df.values.tolist()
        
    style = [
        ('ALIGN', (0, 0), (0, -1), 'LEFT'),  # Left align first column
        ('ALIGN', (1, 0), (-1, -1), 'RIGHT'),  # Right align remaining columns
        ('FONTSIZE', (1, 1), (-1, -1), 10),
    ]

    t = Table(table_data, repeatRows=1, colWidths=[100, 80, 80, 80, 60])
    column_header_style = [('BACKGROUND', (0, 0), (-1, 0), colors.lightgrey),
                        ('TEXTCOLOR', (0, 0), (-1, 0), colors.black),
                        ('ALIGN', (0, 0), (-1, -1), 'LEFT'),
                        ]
    
    t.setStyle(column_header_style)
    t.setStyle(style)
    
    # Remove table borders
    t.setStyle([('LINEBELOW', (0, 0), (-1, 0), 0, colors.white),  # Hide line below header
                ('GRID', (0, 0), (-1, -1), 0, colors.white)])      # Hide grid lines
    
    return t

def add_headers_and_footers(canvas, doc):
    """Add header and footer here"""
    page_num = canvas.getPageNumber()
    text = f"Page {page_num}"
    footer_style = getSampleStyleSheet()['Normal']
    footer_style.alignment = 1  # 0=Left, 1=Center, 2=Right
    
    footer = Paragraph(text, footer_style)
    w, h = footer.wrap(doc.width, doc.bottomMargin - 10)  # Adjusted bottom margin
    footer.drawOn(canvas, doc.leftMargin, doc.bottomMargin - h)

    # Change title text color to white for pages after the first one
    if page_num > 1:
        title_style = getSampleStyleSheet()['Title']
        title_style.textColor = colors.white

def list_process_to_pdf(list_name, header, output_path):
    left_margin = 20
    right_margin = 20
    top_margin = 10
    bottom_margin = 20  # Add a bottom margin
    page_width = A4[0]  # Get width from letter page size
    page_height = A4[1] - top_margin - bottom_margin # Adjust height for margins

    # Create a SimpleDocTemplate with adjusted page size and margins
    doc = SimpleDocTemplate(
        str(output_path),
        pagesize=(page_width, page_height),
        leftMargin=left_margin,
        rightMargin=right_margin,
        topMargin=top_margin,
        bottomMargin=bottom_margin
    )

    company_no = 1
    # Create a list to hold all elements
    elements = []
    
    # header
    styles = getSampleStyleSheet()
    h2_style = styles['Title']
    h2_style.fontSize = 12
    h2_style.Name = 'Arial'
    main_title = Paragraph(header, h2_style)
    elements.extend([main_title])
    for company in list_name:
        # to adjust only 5 company in a single page
        if company_no > 4:
            company_no = 1
            elements.extend([PageBreak()])
        company_no +=1
        if company.isdigit():
            company_int = int(company)
            company_data = combined_df[combined_df['BSE_Code'] == company_int]
        else:
            company = company.upper()
            company_data = combined_df[combined_df['NSE_Code'] == company]
        if not company_data.empty:
            company_name = company_data['Company Name'].values[0]
            nse_code = company_data['NSE_Code'].values[0]
            bse_code = company_data['BSE_Code'].values[0]

            ema10, ema20, ema50, ema200 = averages(nse_code)
            ema_str = "ema10 / ema20 / ema50 / ema200"

            mktcap_value = get_mktcap(nse_code)
            styles = getSampleStyleSheet()

            # adding company info to pdf
            txt = f"Company Name: {company_name} (NSE Code: {nse_code}, BSE Code: {bse_code}, Mktcap: {mktcap_value[0]:,.0f})"
            h2_style = styles['Normal']
            h2_style.fontSize = 11
            h2_style.bold = True
            h2_style.alignment = 0
            main_title = Paragraph(txt, h2_style)
            elements.extend([main_title])

            # ema values
            txt =f"{ema_str} == {ema10[0]}    {ema20[0]}    {ema50[0]}    {ema200[0]}"
            main_title = Paragraph(txt, h2_style)
            elements.extend([main_title])
            # adding space
            elements.extend([Spacer(1, 24)])
            formatted_columns = ['Date', 'NSE_Delivery', 'BSE_Delivery', 'Total_Delivery', 'Price']
            formatted_data = company_data[formatted_columns].copy()
            formatted_data['NSE_Delivery'] = formatted_data['NSE_Delivery'].apply(lambda x: f"{int(x):,}")
            formatted_data['BSE_Delivery'] = formatted_data['BSE_Delivery'].apply(lambda x: f"{int(x):,}")
            formatted_data['Total_Delivery'] = formatted_data['Total_Delivery'].apply(lambda x: f"{int(x):,}")
            formatted_data['Price'] = formatted_data['Price'].apply(lambda x: f"{x:.2f}")

            formatted_data_str = formatted_data.to_string(index=False, col_space={'Date': 9, 'NSE_Delivery': 15, 'BSE_Delivery': 15,
                                                                                   'Total_Delivery': 15, 'Price': 10})
            table_width = doc.width - doc.leftMargin - doc.rightMargin
            table = create_table_with_header(formatted_data, add_column_names=True, table_width=table_width)
            elements.append(table)
            # adding space
            elements.extend([Spacer(1, 24)])
        else:
            txt=f"No data found for {company}\n"
            main_title = Paragraph(txt, h2_style)
            elements.extend([main_title])
        
    doc.build(elements, onFirstPage=add_headers_and_footers, onLaterPages=add_headers_and_footers)

In [152]:
print(heading_3_percent)
print("")
print_formatted_rows(ticker_list,title_3_percent)
print()
print()
print()
list_process_new(ticker_list, heading_3_percent)
list_process_to_pdf(ticker_list, header=heading_3_percent, output_path="titcker_list.pdf")

In [153]:
print_formatted_rows(dely_3x_list,heading_3x)
print()
print()
print()
list_process_new(dely_3x_list, heading_3x)
list_process_to_pdf(dely_3x_list, header=heading_3x, output_path="heading_3x.pdf")

In [154]:

print(heading_non_fno)
print("")
print_formatted_rows(unique_non_fno,title_non_fno)
print()
print()
print()
list_process_new(unique_non_fno, heading_non_fno)
list_process_to_pdf(unique_non_fno, header=heading_non_fno, output_path="heading_non_fno.pdf")

In [155]:
print(heading_sme)
print("")
print_formatted_rows(sme_list,title_sme)
print()
print()
print()
list_process_new(sme_list,heading_sme)
list_process_to_pdf(sme_list, header=heading_sme, output_path="heading_sme.pdf")

In [156]:
print_formatted_rows(holding_list,title_holding)
print()
print()
print()
list_process_new(holding_list, holding_list)
list_process_to_pdf(holding_list, header=holding_list, output_path="holding_list.pdf")

NameError: name 'holding_list' is not defined

In [157]:
print(heading_3_percent_below)
print("")
print_formatted_rows(ticker_below,title_3_percent_below)
print()
print()
print()
list_process_new(ticker_below, heading_3_percent_below)
list_process_to_pdf(ticker_below, header=heading_3_percent_below, output_path="heading_3_percent_below.pdf")

In [158]:
print_formatted_rows(list_above_10k,title_above_10k)
print()
print()
print()
list_process_new(list_above_10k, heading_above_10k)
list_process_to_pdf(list_above_10k, header=heading_above_10k, output_path="heading_above_10k.pdf")

In [159]:
print_formatted_rows(list_1k_10k, title_1k_10k)
print()
print()
print()

list_process_new(list_1k_10k, heading_1k_10k)
list_process_to_pdf(list_1k_10k, header=heading_1k_10k, output_path="heading_1k_10k.pdf")

In [160]:
print_formatted_rows(list_below_1000, title_below_1000)
print()
print()
print()
list_process_new(list_below_1000, heading_below_1000)
list_process_to_pdf(list_below_1000, header=heading_below_1000, output_path="heading_below_1000.pdf")

In [26]:
print("                         Top Deliveries with averages ", report_date)
print('________________________________________________________________________________________________________________')
print("")
print("")
print("")

print_formatted_rows(unique_non_fno,title_non_fno)
print('________________________________________________________________________________________________________________')
print('________________________________________________________________________________________________________________')
print()

print_formatted_rows(sme_list,title_sme)
print('________________________________________________________________________________________________________________')
print('________________________________________________________________________________________________________________')
print()

print_formatted_rows(list_above_10k,title_above_10k)
print('________________________________________________________________________________________________________________')
print('________________________________________________________________________________________________________________')
print()

print_formatted_rows(list_1k_10k,title_1k_10k)
print('________________________________________________________________________________________________________________')
print('________________________________________________________________________________________________________________')
print()

print_formatted_rows(list_below_1000, title_below_1000)
print('________________________________________________________________________________________________________________')
print('________________________________________________________________________________________________________________')
print()

                         Top Deliveries with averages  231226
________________________________________________________________________________________________________________



Non_fno top deliveries 231226 with averages


Company Name                       StockCode      Close PrevClose    MktCap     EMA10     EMA20     EMA50    EMA200


Indian Renewable Energy Dev Ag     IREDA         101.95    109.85    27,399      0.00      0.00      0.00      0.00
Mazagon Dock Shipbuilders Ltd.     MAZDOCK      2287.85   2121.40    46,195      0.00      0.00      0.00      0.00
Castrol India Ltd.                 CASTROLIND    182.55    162.55    18,017      0.00      0.00      0.00      0.00
Adani Green Energy Ltd.            ADANIGREEN   1600.20   1533.10   253,289      0.00      0.00      0.00      0.00
Indian Railway Finance Corpora     IRFC           97.40     97.75   127,287      0.00      0.00      0.00      0.00

Cochin Shipyard Ltd.               COCHINSHIP   1374.50   1301.40    18,061      0.00      0.00      0.00      0.00
JIO Financial Services             JIOFIN        234.70    236.75   149,048      0.00      0.00      0.00      0.00
Mahindra Lifespace Developers      MAHLIFE       540.40    532.35     8,370      0.00      0.00      0.00      0.00
HFCL Ltd.                          HFCL           85.80     82.00    12,260      0.00      0.00      0.00      0.00
                                   LIQUIDBEES    999.99   1000.00         0      0.00      0.00      0.00      0.00

Zomato Ltd.                        ZOMATO        125.00    128.50   108,929      0.00      0.00      0.00      0.00
Adani Energy Solutions             ADANIENSOL   1041.60   1027.90   116,111      0.00      0.00      0.00      0.00
IIFL Finance Ltd.                  IIFL          592.40    572.60    22,559      0.00      0.00      0.00      0.00
Muthoot Microfin Limited           MUTHOOTMF     266.15    291.00         0      0.00      0.00      0.00      0.00
Motisons Jewellers Limited         MOTISONS      103.55     55.00         0      0.00      0.00      0.00      0.00

Varun Beverages Ltd.               VBL          1250.05   1238.60   162,202      0.00      0.00      0.00      0.00
Inox India Limited                 INOXINDIA     928.85    910.65     8,435      0.00      0.00      0.00      0.00
Bharat Dynamics Ltd.               BDL          1694.80   1571.25    31,014      0.00      0.00      0.00      0.00
Ircon International Ltd.           IRCON         171.20    166.60    16,106      0.00      0.00      0.00      0.00
Arman Financial Services Ltd.      ARMANFIN     2508.85   2609.70     2,197      0.00      0.00      0.00      0.00

One97 Communications Ltd.          PAYTM         631.80    642.20    40,117      0.00      0.00      0.00      0.00
Oil India Ltd.                     OIL           381.70    373.25    41,408      0.00      0.00      0.00      0.00
Star Health and Allied Insuran     STARHEALTH    533.80    522.40    31,262      0.00      0.00      0.00      0.00
Yes Bank Ltd.                      YESBANK        20.95     21.05    60,284      0.00      0.00      0.00      0.00
NLC India Ltd.                     NLCINDIA      250.20    223.90    34,741      0.00      0.00      0.00      0.00

Suzlon Energy Ltd.                 SUZLON         36.90     37.25    49,718      0.00      0.00      0.00      0.00
Jupiter Wagons Ltd.                JWL           320.30    323.70    13,202      0.00      0.00      0.00      0.00
Garden Reach Shipbuilders & En     GRSE          872.20    819.65     9,991      0.00      0.00      0.00      0.00
                                   SETFNIF50     223.54    222.74         0      0.00      0.00      0.00      0.00
Solara Active Pharma Sciences      SOLARA        375.95    329.05     1,349      0.00      0.00      0.00      0.00

Himadri Speciality Chemical Lt     HSCL          307.35    286.55    13,561      0.00      0.00      0.00      0.00
Avenue Supermarts Ltd.             DMART        4023.45   4007.95   261,382      0.00      0.00      0.00      0.00
Bank Of India                      BANKINDIA     109.50    111.80    49,807      0.00      0.00      0.00      0.00
BSE Ltd.                           BSE          2310.60   2319.90    31,280      0.00      0.00      0.00      0.00
MSTC Ltd.                          MSTCLTD       643.45    568.00     4,537      0.00      0.00      0.00      0.00

Shyam Metalics And Energy Ltd.     SHYAMMETL     619.10    608.40    15,775      0.00      0.00      0.00      0.00
Suraj Estate Developers Limite     SURAJEST      334.50    360.00         0      0.00      0.00      0.00      0.00
MTAR Technologies Ltd.             MTARTECH     2174.60   2236.65     6,688      0.00      0.00      0.00      0.00
J Kumar Infraprojects Ltd.         JKIL          593.50    494.60     4,491      0.00      0.00      0.00      0.00
Balaji Amines Ltd.                 BALAMINES    2614.60   2365.20     8,461      0.00      0.00      0.00      0.00

Jaiprakash Power Ventures Ltd.     JPPOWER        13.95     13.25     9,519      0.00      0.00      0.00      0.00
Indian Bank                        INDIANB       409.70    412.20    55,118      0.00      0.00      0.00      0.00
Adani Total Gas Ltd.               ATGL          995.05    996.30   109,026      0.00      0.00      0.00      0.00
India Pesticides Ltd.              IPL           369.60    354.55     4,273      0.00      0.00      0.00      0.00
Life Insurance Corporation of      LICI          781.30    792.80   494,048      0.00      0.00      0.00      0.00

JSW Energy Ltd.                    JSWENERGY     415.15    409.30    68,278      0.00      0.00      0.00      0.00
Balmer Lawrie & Company Ltd.       BALMLAWRIE    230.25    224.90     3,941      0.00      0.00      0.00      0.00
Swan Energy Ltd.                   SWANENERGY    503.35    506.40    13,319      0.00      0.00      0.00      0.00
Alkyl Amines Chemicals Ltd.        ALKYLAMINE   2570.90   2304.85    13,124      0.00      0.00      0.00      0.00
Rail Vikas Nigam Ltd.              RVNL          178.65    176.90    37,239      0.00      0.00      0.00      0.00

Syncom Formulations (India) Lt     SYNCOMF        14.15     11.80     1,330      0.00      0.00      0.00      0.00
Akshar Spintex Ltd.                AKSHAR          5.10      5.65       127      0.00      0.00      0.00      0.00
RattanIndia Power Ltd.             RTNPOWER        9.25      9.15     4,967      0.00      0.00      0.00      0.00
Reliance Power Ltd.                RPOWER         22.60     22.40     8,602      0.00      0.00      0.00      0.00
Urja Global Ltd.                   URJA           15.25     14.00       802      0.00      0.00      0.00      0.00

The South Indian Bank Ltd.         SOUTHBANK      26.10     26.65     5,462      0.00      0.00      0.00      0.00
Jaiprakash Associates Ltd.         JPASSOCIAT     20.85     21.10     5,118      0.00      0.00      0.00      0.00
Rajnandini Metal Ltd.              RAJMET         10.55      9.65       292      0.00      0.00      0.00      0.00
PC Jeweller Ltd.                   PCJEWELLER     46.50     51.65     2,164      0.00      0.00      0.00      0.00
Infibeam Avenues Ltd.              INFIBEAM       21.95     21.70     6,096      0.00      0.00      0.00      0.00

Subex Ltd.                         SUBEXLTD       36.70     35.50     2,069      0.00      0.00      0.00      0.00
Hindustan Construction Company     HCC            28.60     29.05     4,321      0.00      0.00      0.00      0.00
TV18 Broadcast Ltd.                TV18BRDCST     52.15     51.00     8,947      0.00      0.00      0.00      0.00
Morepen Laboratories Ltd.          MOREPENLAB     51.85     49.25     2,642      0.00      0.00      0.00      0.00
Dish TV India Ltd.                 DISHTV         19.35     19.75     3,574      0.00      0.00      0.00      0.00

Mishtann Foods Ltd.                539594         17.14     16.44     1,714     16.59     16.25     15.21     12.57
Easy Trip Planners Ltd.            EASEMYTRIP     39.05     38.50     6,785      0.00      0.00      0.00      0.00
NHPC Ltd.                          NHPC           64.60     64.70    64,881      0.00      0.00      0.00      0.00
Brightcom Group Ltd.               BCG            19.35     19.85     3,909      0.00      0.00      0.00      0.00
Hathway Cable & Datacom Ltd.       HATHWAY        22.10     22.05     3,915      0.00      0.00      0.00      0.00

DCW Ltd.                           DCW            57.80     54.85     1,707      0.00      0.00      0.00      0.00

SJVN Ltd.                          SJVN           91.55     89.70    36,029      0.00      0.00      0.00      0.00
Network 18 Media & Investments     NETWORK18      88.85     86.10     9,285      0.00      0.00      0.00      0.00
IRB Infrastructure Developers      IRB            41.85     41.65    25,249      0.00      0.00      0.00      0.00
Orient Green Power Company Ltd     GREENPOWER     21.95     22.35     2,154      0.00      0.00      0.00      0.00

National Fertilizers Ltd.          NFL            85.90     84.25     4,213      0.00      0.00      0.00      0.00
Ultracab (India) Ltd.              538706         27.83     24.30       266     24.50     23.17     20.75     18.94
IFCI Ltd.                          IFCI           28.15     28.40     7,003      0.00      0.00      0.00      0.00
CESC Ltd.                          CESC          123.40    119.15    16,357      0.00      0.00      0.00      0.00
Trident Ltd.                       TRIDENT        36.05     36.15    18,371      0.00      0.00      0.00      0.00

VL E-Governance & IT Solutions     VLEGOV         41.60     34.70       441      0.00      0.00      0.00      0.00
Bajaj Hindusthan Sugar Ltd.        BAJAJHIND      27.75     27.90     3,542      0.00      0.00      0.00      0.00
Union Bank Of India                UNIONBANK     117.15    118.25    86,874      0.00      0.00      0.00      0.00
Himachal Fibres Ltd.               514010         29.67     30.27       256     30.21     28.53     23.47     13.35
Bank Of Maharashtra                MAHABANK       45.25     45.60    32,036      0.00      0.00      0.00      0.00

________________________________________________________________________________________________________________
________________________________________________________________________________________________________________

SME top deliveries 231226 with averages


Company Name                       StockCode      Close PrevClose    MktCap     EMA10     EMA20     EMA50    EMA200


Droneacharya Aerial Innovation     543713        175.20    185.75       420    191.32    190.91    186.08    165.06
Kalyani Cast Tech Limited          544023        446.75    406.15       321    406.53    392.49    352.79    302.71
VishnuSurya Infra                  VISHNUINFR    445.50    428.40     1,096      0.00      0.00      0.00      0.00
Amic Forging Limited               544037        395.90    353.05       415    344.40    317.71    285.61    261.21
Insolation Energy Ltd.             543620        685.00    696.20     1,448    684.06    672.14    607.58    377.44

Basilic Fly Studio                 BASILIC       302.05    301.95       702    294.99    294.44    291.89    288.10
All E Technologies Ltd.            ALLETEC       235.50    256.75       476    249.41    248.40    232.00    170.97
Varanium Cloud Ltd.                CLOUD         100.90    101.95       406    105.37    110.49    123.88    151.01
Gretex Corporate Services Ltd.     543324        328.95    303.50       380    274.85    250.12    230.63    194.69
Presstonic Engineering Limited     PRESSTONIC    137.20    131.65       106      0.00      0.00      0.00      0.00

Waaree Technologies Ltd.           539337        730.30    695.60       786    629.05    571.54    502.72    384.66
S J Logistics                      SJLOGISTIC    168.40    174.10       244      0.00      0.00      0.00      0.00
Phantom Digital Effects Ltd.       PHANTOMFX     491.80    520.30       572    462.86    446.12    437.81    395.67
Cellcor Gadgets                    CELLECOR      289.20    264.20       606    260.08    250.06    227.49    184.22
Indo US Bio-Tech Ltd.              541304        243.10    239.00       491    234.55    223.85    211.51    158.62

Sheetal Universal Limited          SHEETAL        86.10     75.20        99     72.42     73.21     74.27     75.08
HiGreen Carbon                     HIGREEN       180.15    180.80       450    181.45    176.55    164.12    147.34
Kody Techno                        KODYTECH      513.60    428.45       327    404.92    373.19    334.40    284.13
Network People Services Techno     NPST         2316.45   2206.15     1,497   2205.91   2134.80   1655.81    689.18
Concord Control Systems Ltd.       543619        796.80    664.00       477    699.56    690.52    654.54    467.61

Remus Pharmaceuticals Ltd.         REMUS        7587.25   7060.00     1,118   6497.76   6099.95   5628.39   4360.30
Rocking Deals Circular Economy     ROCKINGDCE    312.65    331.90       177      0.00      0.00      0.00      0.00
Benchmark Computer Solutions L     544052         76.93     73.27        53     76.51     76.77     76.97     77.08
RMC Switchgears Ltd.               540358        587.75    578.75       608    584.15    586.85    603.08    515.17
ROX Hitech Limited                 ROXHITECH     165.70    159.15       378    165.07    157.77    149.68    143.97

Graphisads Limited                 GRAPHISAD      76.80     80.80       140     89.33     95.31    100.92    104.57
Chavda Infra                       CHAVDA         86.55     80.10       213     85.21     87.60     89.98     89.21
Supershakti Metaliks Ltd.          541701        460.00    460.00       530    469.52    469.63    442.84    367.48
Accent Microcell Limited           ACCENTMIC     279.45    288.55       588    292.66    300.83    308.38    313.21
Sahara Maritime Limited            544056         81.16      0.00         0     81.16     81.16     81.16     81.16

Taylormade Renewables Ltd.         541228        766.35    729.90       842    720.73    714.72    664.48    474.42
Vinyas Innovative Technologies     VINYAS        751.65    735.55       946    609.65    550.22    499.33    470.00
Bondada Engineering Limited        543971        379.75    391.75       817    395.87    397.40    359.02    242.00
Oriana Power Limited               ORIANA        496.60    501.80       953    485.79    453.83    404.22    380.93
Cosmic CRF Ltd.                    543928        446.85    413.70       312    400.68    374.89    331.56    276.80

SAR Televenture Ltd                SARTELE       164.85    171.35       247    101.68    104.07    107.05    109.33
Essen Speciality Films Ltd.        ESFL          210.60    214.10       436    218.33    213.12    192.86    159.23
Jayant Infratech Ltd.              543544        197.30    190.10       194    180.18    163.94    134.67    105.31
Paragon Fine and Speciality Ch     PARAGON       137.10    145.00       268    199.57    203.10    208.10    212.11
Crop Life Science Limited          CLSL           47.55     42.40        82     42.16     41.39     41.33     43.30

Sahana System Ltd.                 SAHANA        647.95    617.10       518    594.64    577.04    501.24    308.95
Arihant Academy Ltd.               ARIHANTACA    171.70    173.55       104      0.00      0.00      0.00      0.00
Baba Food Processing Private L     BABAFP         69.45     65.30       113     73.30     72.70     72.36     72.23
Dev Labtech Venture Ltd.           543848         84.75     88.47        70     80.42     78.66     74.83     64.52
Transteel Seating Technologies     TRANSTEEL      80.95     83.80       163     98.62     97.76     95.80     94.04

Viaz Tyres Ltd.                    VIAZ           66.80     58.05        82     56.38     51.94     47.73     49.40
Rachana Infrastructure Ltd.        RILINFRA       86.20     88.00       160     88.97     90.90     95.95    186.86
Kundan Edifice                     KEL           239.70    252.30       246    228.72    199.85    151.05     99.97
Kotyark Industries Ltd.            KOTYARK       947.80    954.90       828    942.45    909.44    838.68    653.65
Synoptics Technologies Ltd.        SYNOPTICS     134.10    128.00       114    130.05    129.57    130.71    144.91

________________________________________________________________________________________________________________
________________________________________________________________________________________________________________

         Top deliveries mktcap above 10k cr 231226 with averages


Company Name                       StockCode      Close PrevClose    MktCap     EMA10     EMA20     EMA50    EMA200


Adani Power Ltd.                   ADANIPOWER    511.70    512.55   197,823      0.00      0.00      0.00      0.00
Amber Enterprises India Ltd.       AMBER        3041.15   3051.55    10,245      0.00      0.00      0.00      0.00
Angel One Ltd.                     ANGELONE     3288.20   3292.35    27,611      0.00      0.00      0.00      0.00
Bikaji Foods International Ltd     BIKAJI        553.30    552.35    13,823      0.00      0.00      0.00      0.00
Blue Star Ltd.                     BLUESTARCO    946.95    951.25    19,465      0.00      0.00      0.00      0.00

Brigade Enterprises Ltd.           BRIGADE       859.50    868.80    19,992      0.00      0.00      0.00      0.00
BSE Ltd.                           BSE          2310.60   2319.90    31,280      0.00      0.00      0.00      0.00

Central Depository Services (I     CDSL         1851.05   1836.95    19,343      0.00      0.00      0.00      0.00
Cello World Limited                CELLO         765.50    769.20    16,257      0.00      0.00      0.00      0.00
Concord Biotech                    CONCORDBIO   1506.10   1504.70    15,715      0.00      0.00      0.00      0.00

CreditAccess Grameen Ltd.          CREDITACC    1613.25   1627.50    25,711      0.00      0.00      0.00      0.00
Elecon Engineering Company Ltd     ELECON        940.25    893.50    10,549      0.00      0.00      0.00      0.00
Vodafone Idea Ltd.                 IDEA           13.35     13.60    65,037      0.00      0.00      0.00      0.00
Jindal Saw Ltd.                    JINDALSAW     422.15    424.40    13,481      0.00      0.00      0.00      0.00
JK Cement Ltd.                     JKCEMENT     3765.40   3782.20    29,238      0.00      0.00      0.00      0.00

Jupiter Wagons Ltd.                JWL           320.30    323.70    13,202      0.00      0.00      0.00      0.00
KPIT Technologies Ltd.             KPITTECH     1527.70   1539.35    41,870      0.00      0.00      0.00      0.00
L&T Finance Holdings Ltd.          L&TFH         153.00    152.80    38,048      0.00      0.00      0.00      0.00
Dr. Lal Pathlabs Ltd.              LALPATHLAB   2600.05   2596.50    21,721      0.00      0.00      0.00      0.00
Macrotech Developers Ltd.          LODHA         952.80    937.20    91,717      0.00      0.00      0.00      0.00

Multi Commodity Exchange Of In     MCX          3144.15   3163.85    16,043      0.00      0.00      0.00      0.00
Global Health Ltd.                 MEDANTA       963.65    973.85    26,139      0.00      0.00      0.00      0.00
Patanjali Foods Ltd.               PATANJALI    1617.90   1621.65    58,509      0.00      0.00      0.00      0.00
One97 Communications Ltd.          PAYTM         631.80    642.20    40,117      0.00      0.00      0.00      0.00
The Phoenix Mills Ltd.             PHOENIXLTD   2304.85   2298.50    41,150      0.00      0.00      0.00      0.00

PI Industries Ltd.                 PIIND        3451.85   3427.95    52,439      0.00      0.00      0.00      0.00
Poonawalla Fincorp Ltd.            POONAWALLA    440.25    442.35    33,895      0.00      0.00      0.00      0.00
Piramal Pharma Ltd.                PPLPHARMA     138.60    140.50    18,356      0.00      0.00      0.00      0.00
Prestige Estates Projects Ltd.     PRESTIGE     1121.30   1114.90    44,972      0.00      0.00      0.00      0.00
Radico Khaitan Ltd.                RADICO       1615.15   1602.50    21,588      0.00      0.00      0.00      0.00

REC Ltd.                           RECLTD        419.00    406.60   110,306      0.00      0.00      0.00      0.00
Ramkrishna Forgings Ltd.           RKFORGE       724.65    724.40    13,026      0.00      0.00      0.00      0.00
Shriram Finance Ltd.               SHRIRAMFIN   2035.75   2055.45    76,297      0.00      0.00      0.00      0.00
Solar Industries India Ltd.        SOLARINDS    6793.15   6594.90    61,544      0.00      0.00      0.00      0.00
Sonata Software Ltd.               SONATSOFTW    744.55    749.90    20,879      0.00      0.00      0.00      0.00

Suzlon Energy Ltd.                 SUZLON         36.90     37.25    49,718      0.00      0.00      0.00      0.00
Swan Energy Ltd.                   SWANENERGY    503.35    506.40    13,319      0.00      0.00      0.00      0.00
Tata Motors Ltd.                   TATAMOTORS    719.55    724.70   263,725      0.00      0.00      0.00      0.00
Titagarh Railsystems Ltd.          TITAGARH     1038.90   1047.85    14,024      0.00      0.00      0.00      0.00
Trent Ltd.                         TRENT        2970.00   2965.50   105,617      0.00      0.00      0.00      0.00

Union Bank Of India                UNIONBANK     117.15    118.25    86,874      0.00      0.00      0.00      0.00
Welspun Corp Ltd.                  WELCORP       545.10    530.55    14,270      0.00      0.00      0.00      0.00
Zomato Ltd.                        ZOMATO        125.00    128.50   108,929      0.00      0.00      0.00      0.00
________________________________________________________________________________________________________________
________________________________________________________________________________________________________________

          Top deliveries mktcap 1k - 10k cr 231226 with averages


Company Name                       StockCode      Close PrevClose    MktCap     EMA10     EMA20     EMA50    EMA200


Balu Forge Industries Ltd.         531112        250.95    248.20     2,575    246.74    243.97    234.44    182.80
BMW Industries Ltd.                542669         54.67     52.45     1,231     54.90     54.94     51.43     41.25
Insolation Energy Ltd.             543620        685.00    696.20     1,448    684.06    672.14    607.58    377.44
Anant Raj Ltd.                     ANANTRAJ      299.05    303.15     9,713      0.00      0.00      0.00      0.00
The Anup Engineering Ltd.          ANUP         2732.00   2638.00     2,715      0.00      0.00      0.00      0.00

Apollo Micro Systems Ltd.          APOLLO        114.05    114.70     2,987      0.00      0.00      0.00      0.00
Arvind Ltd.                        ARVIND        266.35    259.30     6,952      0.00      0.00      0.00      0.00
Arvind Fashions Ltd.               ARVINDFASN    419.20    412.15     5,563      0.00      0.00      0.00      0.00
Antony Waste Handling Cell Ltd     AWHCL         501.50    488.80     1,417      0.00      0.00      0.00      0.00
Bajaj Hindusthan Sugar Ltd.        BAJAJHIND      27.75     27.90     3,542      0.00      0.00      0.00      0.00

Banco Products (India) Ltd.        BANCOINDIA    651.05    618.75     4,642      0.00      0.00      0.00      0.00
BCL Industries Ltd.                BCLIND         65.95     66.50     1,672      0.00      0.00      0.00      0.00
Blue Jet Healthcare Limited        BLUEJET       369.65    361.30     6,439      0.00      0.00      0.00      0.00
Cigniti Technologies Ltd.          CIGNITITEC   1108.65   1125.75     3,022      0.00      0.00      0.00      0.00
Cupid Ltd.                         CUPID         967.90    921.85     1,291      0.00      0.00      0.00      0.00

DB Realty Ltd.                     DBREALTY      187.55    191.85     9,419      0.00      0.00      0.00      0.00
Prataap Snacks Ltd.                DIAMONDYD    1024.40    965.55     2,472      0.00      0.00      0.00      0.00
Dollar Industries Ltd.             DOLLAR        449.70    440.10     2,549      0.00      0.00      0.00      0.00
Electrosteel Castings Ltd.         ELECTCAST     114.45    112.90     6,811      0.00      0.00      0.00      0.00
Electronics Mart India Ltd.        EMIL          203.30    205.70     7,501      0.00      0.00      0.00      0.00

Focus Lighting & Fixtures Ltd.     FOCUS         179.15    177.20     1,187      0.00      0.00      0.00      0.00
Gabriel India Ltd.                 GABRIEL       397.70    403.60     5,733      0.00      0.00      0.00      0.00
Gensol Engineering Ltd.            GENSOL        767.05    768.80     2,956      0.00      0.00      0.00      0.00
Genus Power Infrastructures Lt     GENUSPOWER    228.05    231.15     5,864      0.00      0.00      0.00      0.00
Hariom Pipe Industries Ltd.        HARIOMPIPE    635.45    634.15     1,756      0.00      0.00      0.00      0.00

HBL Power Systems Ltd.             HBLPOWER      445.80    443.30    12,359      0.00      0.00      0.00      0.00
Hindustan Construction Company     HCC            28.60     29.05     4,321      0.00      0.00      0.00      0.00
Hind Rectifiers Ltd.               HIRECT        554.70    551.95       943      0.00      0.00      0.00      0.00
Hi-Tech Pipes Ltd.                 HITECH        112.25     99.95     1,538      0.00      0.00      0.00      0.00
HPL Electric & Power Ltd.          HPL           210.40    214.15     1,354      0.00      0.00      0.00      0.00

Indo Count Industries Ltd.         ICIL          295.35    293.15     5,842      0.00      0.00      0.00      0.00
IFGL Refractories Ltd.             IFGLEXPOR     789.50    767.40     2,859      0.00      0.00      0.00      0.00
IIFL Securities Ltd.               IIFLSEC       145.60    137.40     4,520      0.00      0.00      0.00      0.00
IKIO Lighting Ltd.                 IKIO          335.80    342.90     2,594      0.00      0.00      0.00      0.00

Indraprastha Medical Corporati     INDRAMEDCO    178.65    179.55     1,645      0.00      0.00      0.00      0.00

Inox Wind Ltd.                     INOXWIND      466.15    453.25    15,183      0.00      0.00      0.00      0.00
JK Lakshmi Cement Ltd.             JKLAKSHMI     885.55    870.05    10,372      0.00      0.00      0.00      0.00
JK Tyre & Industries Ltd.          JKTYRE        377.40    383.30     9,290      0.00      0.00      0.00      0.00
Jaiprakash Associates Ltd.         JPASSOCIAT     20.85     21.10     5,118      0.00      0.00      0.00      0.00
Jaiprakash Power Ventures Ltd.     JPPOWER        13.95     13.25     9,519      0.00      0.00      0.00      0.00

Sai Kalamandir                     KALAMANDIR    274.90    277.50     4,219      0.00      0.00      0.00      0.00
Kesoram Industries Ltd.            KESORAMIND    168.95    167.05     5,241      0.00      0.00      0.00      0.00
KFin Technologies Ltd.             KFINTECH      502.60    491.85     8,555      0.00      0.00      0.00      0.00
KPI Green Energy Ltd.              KPIGREEN     1331.10   1342.40     4,999      0.00      0.00      0.00      0.00
LT Foods Ltd.                      LTFOODS       203.45    200.65     7,080      0.00      0.00      0.00      0.00

Lumax Auto Technologies Ltd.       LUMAXTECH     389.15    384.25     2,658      0.00      0.00      0.00      0.00
Man Industries (India) Ltd.        MANINDS       251.85    251.10     1,508      0.00      0.00      0.00      0.00
Marine Electricals (India) Ltd     MARINE         99.50     97.75     1,289      0.00      0.00      0.00      0.00
Marksans Pharma Ltd.               MARKSANS      158.70    160.05     7,214      0.00      0.00      0.00      0.00
MOIL Ltd.                          MOIL          305.90    306.30     6,231      0.00      0.00      0.00      0.00

Manoj Vaibhav                      MVGJL         334.75    328.70     1,635      0.00      0.00      0.00      0.00
Neuland Laboratories Ltd.          NEULANDLAB   5329.70   5115.50     6,844      0.00      0.00      0.00      0.00
Newgen Software Technologies L     NEWGEN       1509.55   1438.55    10,582      0.00      0.00      0.00      0.00
Parag Milk Foods Ltd.              PARAGMILK     236.55    237.35     2,775      0.00      0.00      0.00      0.00
Peninsula Land Ltd.                PENINLAND      51.80     50.30     1,510      0.00      0.00      0.00      0.00

PTC India Financial Services L     PFS            41.85     42.50     2,682      0.00      0.00      0.00      0.00
Pokarna Ltd.                       POKARNA       490.00    481.75     1,519      0.00      0.00      0.00      0.00
Premier Explosives Ltd.            PREMEXPLN    1612.90   1603.20     1,748      0.00      0.00      0.00      0.00
Prism Johnson Ltd.                 PRSMJOHNSN    182.00    181.00     9,179      0.00      0.00      0.00      0.00
Ramky Infrastructure Ltd.          RAMKY         789.85    796.30     5,439      0.00      0.00      0.00      0.00

RateGain Travel Technologies L     RATEGAIN      730.10    740.20     8,699      0.00      0.00      0.00      0.00
Repco Home Finance Ltd.            REPCOHOME     396.75    396.75     2,482      0.00      0.00      0.00      0.00
RPG Life Sciences Ltd.             RPGLIFE      1369.05   1363.40     2,275      0.00      0.00      0.00      0.00
Sadhana Nitro Chem Ltd.            SADHNANIQ      86.75     85.80     2,144      0.00      0.00      0.00      0.00
Sanghvi Movers Ltd.                SANGHVIMOV    825.65    835.60     3,581      0.00      0.00      0.00      0.00

Satin Creditcare Network Ltd.      SATIN         242.10    252.75     2,677      0.00      0.00      0.00      0.00
Som Distilleries Breweries & W     SDBL          288.95    291.65     2,238      0.00      0.00      0.00      0.00
Senco Gold Ltd.                    SENCO         722.30    727.55     5,612      0.00      0.00      0.00      0.00
SEPC Ltd.                          SEPC           20.85     21.00     2,946      0.00      0.00      0.00      0.00
Shriram Pistons & Rings Ltd        SHRIPISTON   1341.30   1277.45     5,908      0.00      0.00      0.00      0.00

Shriram Properties Ltd.            SHRIRAMPPS    120.55    119.05     2,052      0.00      0.00      0.00      0.00
Skipper Ltd.                       SKIPPER       224.95    225.85     2,315      0.00      0.00      0.00      0.00
Somany Ceramics Ltd.               SOMANYCERA    716.95    726.75     3,027      0.00      0.00      0.00      0.00
Spandana Sphoorty Financial Lt     SPANDANA     1029.70   1036.55     7,347      0.00      0.00      0.00      0.00
Transport Corporation Of India     TCI           818.15    816.75     6,352      0.00      0.00      0.00      0.00

TD Power Systems Ltd.              TDPOWERSYS    266.00    267.55     4,141      0.00      0.00      0.00      0.00
Thomas Cook (India) Ltd.           THOMASCOOK    140.30    139.80     6,576      0.00      0.00      0.00      0.00
Transformers & Rectifiers (Ind     TRIL          217.40    224.05     3,117      0.00      0.00      0.00      0.00
TV18 Broadcast Ltd.                TV18BRDCST     52.15     51.00     8,947      0.00      0.00      0.00      0.00
Vijaya Diagnostic Centre Ltd.      VIJAYA        630.80    640.90     6,458      0.00      0.00      0.00      0.00

Zaggle Prepaid                     ZAGGLE        221.75    224.45     2,709      0.00      0.00      0.00      0.00
Zee Media Corporation Ltd.         ZEEMEDIA       15.40     15.70       959      0.00      0.00      0.00      0.00
________________________________________________________________________________________________________________
________________________________________________________________________________________________________________

         Top deliveries mktcap below 1000 cr 231226 with averages


Company Name                       StockCode      Close PrevClose    MktCap     EMA10     EMA20     EMA50    EMA200


20 Microns Ltd.                    20MICRONS     188.95    189.45       667      0.00      0.00      0.00      0.00
Kilburn Engineering Ltd.           522101        281.70    280.80     1,067    282.14    278.92    255.32    179.65
Nile Ltd.                          530129        874.75    882.10       262    878.40    881.02    844.51    735.64
Ceinsys Tech Ltd.                  538734        351.45    356.30       542    356.46    356.08    336.10    251.65
RMC Switchgears Ltd.               540358        587.75    578.75       608    584.15    586.85    603.08    515.17

Khazanchi Jewellers Ltd            543953        274.00    273.15       678    274.50    276.12    264.36    207.34
Bondada Engineering Limited        543971        379.75    391.75       817    395.87    397.40    359.02    242.00
Annapurna Swadisht Ltd.            ANNAPURNA     319.50    323.80       556    331.49    334.41    326.04    278.64
Arihant Superstructures Ltd.       ARIHANTSUP    269.05    261.55     1,118      0.00      0.00      0.00      0.00
Chembond Chemicals Ltd.            CHEMBOND      546.40    550.45       733      0.00      0.00      0.00      0.00

Dharmaj Crop Guard Ltd.            DHARMAJ       263.25    258.45       900      0.00      0.00      0.00      0.00
Global Education Ltd.              GLOBAL        311.00    308.75       633      0.00      0.00      0.00      0.00
Indo Tech Transformers Ltd.        INDOTECH      629.05    599.10       668      0.00      0.00      0.00      0.00
Kapston Services Ltd.              KAPSTON       246.85    235.10       250      0.00      0.00      0.00      0.00
Kothari Petrochemicals Ltd.        KOTHARIPET    152.45    147.55       897      0.00      0.00      0.00      0.00

Magson Retail & Distribution L     MAGSON        134.80    134.75       106    129.73    125.84    115.22     95.25
MBL Infrastructure Ltd.            MBLINFRA       46.15     45.25       477      0.00      0.00      0.00      0.00
Modison Ltd.                       MODISONLTD    130.55    132.20       423      0.00      0.00      0.00      0.00
NDR Auto Components Ltd.           NDRAUTO       778.25    747.00       925      0.00      0.00      0.00      0.00

Pyramid Technoplast Limited        PYRAMID       195.85    192.90       722      0.00      0.00      0.00      0.00

Semac Consultants Ltd              SEMAC        2303.00   2350.00       708      0.00      0.00      0.00      0.00
Sky Gold Ltd.                      SKYGOLD      1003.90    956.10     1,079      0.00      0.00      0.00      0.00
Venus Remedies Ltd.                VENUSREM      395.80    389.95       527      0.00      0.00      0.00      0.00
Walchandnagar Industries Ltd.      WALCHANNAG    196.95    187.60       905      0.00      0.00      0.00      0.00
________________________________________________________________________________________________________________
________________________________________________________________________________________________________________

In [25]:
check_stock = ['inspirisys','coalindia','wockpharma', 'imagicaa','stltech','cub','sagcem','sapphire']
list_process_new(check_stock, "temp check")

temp check
Company Name: Inspirisys Solutions Ltd. (NSE Code: INSPIRISYS, BSE Code: 532774, Mktcap:338, Networth:-9)

ema10 / ema20 / ema50 / ema200     0  0  0  0

     Date    NSE_Delivery    BSE_Delivery  Total_Delivery      Price
   231020           5,181           3,753           8,934      71.45
   231010           7,170           1,545           8,715      63.30
   230810           1,354           1,729           3,083      78.45
   230420           6,390           2,960           9,350      54.15
   190124             932               2             934      56.00

==================================================


Company Name: Coal India Ltd. (NSE Code: COALINDIA, BSE Code: 533278, Mktcap:225,618, Networth:69,686)

ema10 / ema20 / ema50 / ema200     0  0  0  0

     Date    NSE_Delivery    BSE_Delivery  Total_Delivery      Price
   231020       2,305,726          46,430       2,352,156     312.40
   231010       8,636,371         172,611       8,808,982     303.25
   230810       5,663,735          71,336       5,735,071     234.90
   230420       1,019,622          81,105       1,100,727     229.55
   190124       1,553,925          53,657       1,607,582     223.85

==================================================


Company Name: Wockhardt Ltd. (NSE Code: WOCKPHARMA, BSE Code: 532300, Mktcap:6,046, Networth:3,125)

ema10 / ema20 / ema50 / ema200     0  0  0  0

     Date    NSE_Delivery    BSE_Delivery  Total_Delivery      Price
   231020         267,803          24,348         292,151     244.15
   231010         140,470          19,106         159,576     230.85
   230810         545,482          42,393         587,875     256.55
   230420         246,988          32,599         279,587     173.75
   190124         128,109          15,878         143,987     483.60

==================================================


Company Name: Imagicaaworld Entertainment Lt (NSE Code: IMAGICAA, BSE Code: 539056, Mktcap:2,855, Networth:785)

ema10 / ema20 / ema50 / ema200     0  0  0  0

     Date    NSE_Delivery    BSE_Delivery  Total_Delivery      Price
   231020         519,217          62,356         581,573      48.80
   231010         497,507          15,653         513,160      50.50
   230810       1,548,161         144,637       1,692,798      57.25
   230420         242,380          30,466         272,846      44.50
   190124               0          33,404          33,404       9.82

==================================================


Company Name: Sterlite Technologies Ltd. (NSE Code: STLTECH, BSE Code: 532374, Mktcap:5,742, Networth:2,136)

ema10 / ema20 / ema50 / ema200     0  0  0  0

     Date    NSE_Delivery    BSE_Delivery  Total_Delivery      Price
   231020       1,484,941         108,245       1,593,186     165.00
   231010         267,913          30,865         298,778     155.95
   230810       1,011,244          63,444       1,074,688     154.55
   230420         219,011          22,578         241,589     158.25
   190124               0          92,456          92,456     290.10

==================================================


Company Name: City Union Bank Ltd. (NSE Code: CUB, BSE Code: 532210, Mktcap:11,021, Networth:7,457)

ema10 / ema20 / ema50 / ema200     0  0  0  0

     Date    NSE_Delivery    BSE_Delivery  Total_Delivery      Price
   231020       1,173,757       1,064,573       2,238,330     136.45
   231010       8,775,549         865,242       9,640,791     134.75
   230810         596,648          33,856         630,504     132.65
   230420       2,017,893         185,579       2,203,472     133.20
   190124         754,537           7,277         761,814     190.05

==================================================


Company Name: Sagar Cements Ltd. (NSE Code: SAGCEM, BSE Code: 502090, Mktcap:3,382, Networth:1,582)

ema10 / ema20 / ema50 / ema200     0  0  0  0

     Date    NSE_Delivery    BSE_Delivery  Total_Delivery      Price
   231020         394,490          48,561         443,051     258.30
   231010          27,615           4,930          32,545     232.80
   230810         142,502          11,929         154,431     242.50
   230420          35,646           2,675          38,321     194.05
   190124             218               1             219     625.30

==================================================


Company Name: Sapphire Foods India Ltd. (NSE Code: SAPPHIRE, BSE Code: 543397, Mktcap:9,095, Networth:1,311)

ema10 / ema20 / ema50 / ema200     0  0  0  0

     Date    NSE_Delivery    BSE_Delivery  Total_Delivery      Price
   231020          51,838             273          52,111    1408.15
   231010          92,188             782          92,970    1406.40
   230810          18,406             490          18,896    1362.70
   230420          33,560             317          33,877    1194.85

==================================================

In [85]:
from reportlab.lib.pagesizes import letter, A4
from reportlab.pdfgen import canvas
from reportlab.lib import colors
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle

def create_table_with_header(df, add_column_names=False, table_width=None):
    """create a table with header and data"""
    table_data = [df.columns.tolist()] + df.values.tolist()
        
    style = [
        ('ALIGN', (0, 0), (0, -1), 'LEFT'),  # Left align first column
        ('ALIGN', (1, 0), (-1, -1), 'RIGHT'),  # Right align remaining columns
    ]

    t = Table(table_data, repeatRows=1, colWidths=[100, 80, 80, 80, 60])
    column_header_style = [('BACKGROUND', (0, 0), (-1, 0), colors.lightgrey),
                        ('TEXTCOLOR', (0, 0), (-1, 0), colors.black),
                        ('ALIGN', (0, 0), (-1, -1), 'LEFT'),
                        ]
    
    t.setStyle(column_header_style)
    t.setStyle(style)
    
    # Remove table borders
    t.setStyle([('LINEBELOW', (0, 0), (-1, 0), 0, colors.white),  # Hide line below header
                ('GRID', (0, 0), (-1, -1), 0, colors.white)])      # Hide grid lines
    
    return t

def add_headers_and_footers(canvas, doc):
    """Add header and footer here"""
    page_num = canvas.getPageNumber()
    text = f"Page {page_num}"
    footer_style = getSampleStyleSheet()['Normal']
    footer_style.alignment = 1  # 0=Left, 1=Center, 2=Right

    footer = Paragraph(text, footer_style)
    w, h = footer.wrap(doc.width, doc.bottomMargin)
    footer.drawOn(canvas, doc.leftMargin, doc.bottomMargin - h)

    # Change title text color to white for pages after the first one
    if page_num > 1:
        title_style = getSampleStyleSheet()['Title']
        title_style.textColor = colors.white

def list_process_to_pdf(list_name, header, output_path):
    left_margin = 20
    right_margin = 20
    top_margin = 5
    bottom_margin = 20  # Add a bottom margin
    page_width = A4[0]  # Get width from letter page size
    page_height = A4[1] - top_margin - bottom_margin  # Adjust height for margins

    # Create a SimpleDocTemplate with adjusted page size and margins
    doc = SimpleDocTemplate(
        str(output_path),
        pagesize=(page_width, page_height),
        leftMargin=left_margin,
        rightMargin=right_margin,
        topMargin=top_margin,
        bottomMargin=bottom_margin
    )

    # Create a list to hold all elements
    elements = []
    for company in list_name:
        if company.isdigit():
            company_int = int(company)
            company_data = combined_df[combined_df['BSE_Code'] == company_int]
        else:
            company = company.upper()
            company_data = combined_df[combined_df['NSE_Code'] == company]

        if not company_data.empty:
            company_name = company_data['Company Name'].values[0]
            nse_code = company_data['NSE_Code'].values[0]
            bse_code = company_data['BSE_Code'].values[0]

            ema10, ema20, ema50, ema200 = averages(nse_code)
            ema_str = "ema10 / ema20 / ema50 / ema200"

            mktcap_value = get_mktcap(nse_code)

            # adding company info to pdf
            txt = f"Company Name: {company_name} (NSE Code: {nse_code}, BSE Code: {bse_code}, Mktcap: {mktcap_value[0]:,.0f})"
            styles = getSampleStyleSheet()
            h2_style = styles['Normal']
            h2_style.fontSize = 11
            h2_style.Name = 'Arial'
            h2_style.bold = True
            h2_style.alignment = 0 
            main_title = Paragraph(txt, h2_style)
            elements.extend([main_title])
            txt =f"{ema_str}     {ema10[0]}  {ema20[0]}  {ema50[0]}  {ema200[0]}"

            h2_style.fontSize = 10
            main_title = Paragraph(txt, h2_style)
            elements.extend([main_title])

            formatted_columns = ['Date', 'NSE_Delivery', 'BSE_Delivery', 'Total_Delivery', 'Price']
            formatted_data = company_data[formatted_columns].copy()
            formatted_data['NSE_Delivery'] = formatted_data['NSE_Delivery'].apply(lambda x: f"{int(x):,}")
            formatted_data['BSE_Delivery'] = formatted_data['BSE_Delivery'].apply(lambda x: f"{int(x):,}")
            formatted_data['Total_Delivery'] = formatted_data['Total_Delivery'].apply(lambda x: f"{int(x):,}")
            formatted_data['Price'] = formatted_data['Price'].apply(lambda x: f"{x:.2f}")

            formatted_data_str = formatted_data.to_string(index=False, col_space={'Date': 9, 'NSE_Delivery': 15, 'BSE_Delivery': 15,
                                                                                   'Total_Delivery': 15, 'Price': 10})
            table_width = doc.width - doc.leftMargin - doc.rightMargin
            table = create_table_with_header(formatted_data, add_column_names=True, table_width=table_width)
            elements.append(table)
            # adding space
            elements.extend([Spacer(1, 24)])
        else:
            txt=f"No data found for {company}\n"
            main_title = Paragraph(txt, h2_style)
            elements.extend([main_title])
        
    doc.build(elements, onFirstPage=add_headers_and_footers, onLaterPages=add_headers_and_footers)

In [86]:
list_process_to_pdf(check_stock, "temp check", "output_a4_spacing_1_reduced_testing.pdf")